const de = {
  nav: { home: "Startseite", adopt: "Adoptieren", reviews: "Bewertungen", foster: "Pflegestelle", donate: "Spenden", about: "Über uns", breeds: "Rassen", catBreeds: "Katzenrassen", dogBreeds: "Hunderassen", more: "Mehr", deliveryOptions: "Lieferoptionen", healthGuarantee: "Gesundheitsgarantie", emotionalSupport: "Emotionale Unterstützung", contact: "Kontakt", startAdopting: "Jetzt Adoptieren", signIn: "Anmelden", signOut: "Abmelden", admin: "Admin", orders: "Bestellungen", orderHistory: "Bestellverlauf", account: "Kontoeinstellungen", adminDashboard: "Admin-Dashboard", cart: "Warenkorb", language: "Sprache", currency: "Währung", shoppingCart: "Warenkorb", item: "Artikel", items: "Artikel", cartEmpty: "Ihr Warenkorb ist leer", browsePets: "Tiere durchsuchen", subtotal: "Zwischensumme", proceedToCheckout: "Zur Kasse", moreItems: "+{{count}} weiterer Artikel", moreItems_plural: "+{{count}} weitere Artikel", deposit: "30% Anzahlung", fullAdoption: "Vollständige Adoption" },
  hero: { title: "Finden Sie Ihren perfekten Begleiter", subtitle: "Wir verbinden liebevolle Familien mit Haustieren weltweit über unser vertrauenswürdiges globales Netzwerk.", cta: "Verfügbare Tiere ansehen" },
  common: { learnMore: "Mehr erfahren", getStarted: "Loslegen", submit: "Absenden", cancel: "Abbrechen", save: "Speichern", delete: "Löschen", edit: "Bearbeiten", close: "Schließen", loading: "Laden...", error: "Etwas ist schiefgelaufen", success: "Erfolg", viewAll: "Alle anzeigen", readMore: "Weiterlesen", back: "Zurück", next: "Weiter", previous: "Zurück", search: "Suchen", filter: "Filtern", sort: "Sortieren", noResults: "Keine Ergebnisse" },
  pets: { available: "Verfügbar", pending: "Ausstehend", adopted: "Adoptiert", age: "Alter", breed: "Rasse", gender: "Geschlecht", size: "Größe", location: "Standort", adoptionFee: "Adoptionsgebühr", vaccinated: "Geimpft", neutered: "Kastriert", microchipped: "Gechippt", goodWithKids: "Kinderfreundlich", goodWithPets: "Tierfreundlich", houseTrained: "Stubenrein", addToCart: "In den Warenkorb", reserveNow: "Jetzt Reservieren", description: "Beschreibung", healthInfo: "Gesundheitsinfo", deliveryInfo: "Lieferinformationen" },
  delivery: { title: "Lieferoptionen", subtitle: "Weltweiter Tiertransport mit dynamischer entfernungsbasierter Preisgestaltung", groundTransport: "Bodentransport", airCargo: "Luftfracht", flightCompanion: "Flugbegleiter", companion: "Begleiter", distanceBased: "Entfernungsbasiert", estimatedDuration: "Geschätzte Dauer", safetyCompliance: "Sicherheit & Compliance" },
  about: { title: "Über PawsFam", subtitle: "Unser globales Netzwerk", howItWorks: "So funktioniert's", ourCommitment: "Unser Versprechen" },
  footer: { rights: "Alle Rechte vorbehalten.", privacy: "Datenschutz", terms: "AGB" },
  auth: { signIn: "Anmelden", signUp: "Registrieren", email: "E-Mail", password: "Passwort", forgotPassword: "Passwort vergessen?", noAccount: "Kein Konto?", hasAccount: "Bereits ein Konto?" },
  checkout: { title: "Kasse", orderSummary: "Bestellübersicht", paymentMethod: "Zahlungsmethode", placeOrder: "Bestellen", total: "Gesamt" },
};
export default de;
