const el = {
  nav: { home: "Αρχική", adopt: "Υιοθέτησε", reviews: "Κριτικές", foster: "Φιλοξενία", donate: "Δωρεά", about: "Σχετικά", breeds: "Ράτσες", catBreeds: "Ράτσες Γάτας", dogBreeds: "Ράτσες Σκύλου", more: "Περισσότερα", deliveryOptions: "Επιλογές Παράδοσης", healthGuarantee: "Εγγύηση Υγείας", emotionalSupport: "Συναισθηματική Υποστήριξη", contact: "Επικοινωνία", startAdopting: "Ξεκινήστε την Υιοθεσία", signIn: "Σύνδεση", signOut: "Αποσύνδεση", admin: "Διαχ/ση", orders: "Παραγγελίες", orderHistory: "Ιστορικό Παραγγελιών", account: "Ρυθμίσεις Λογαριασμού", adminDashboard: "Πίνακας Διαχείρισης", cart: "Καλάθι", language: "Γλώσσα", currency: "Νόμισμα", shoppingCart: "Καλάθι Αγορών", item: "αντικείμενο", items: "αντικείμενα", cartEmpty: "Το καλάθι σας είναι άδειο", browsePets: "Δείτε Ζώα", subtotal: "Μερικό Σύνολο", proceedToCheckout: "Προχωρήστε στην Πληρωμή", moreItems: "+{{count}} ακόμα", moreItems_plural: "+{{count}} ακόμα", deposit: "Προκαταβολή 30%", fullAdoption: "Πλήρης Υιοθεσία" },
  hero: { title: "Βρείτε τον Ιδανικό Σύντροφο", subtitle: "Συνδέουμε αγαπημένες οικογένειες με κατοικίδια σε όλο τον κόσμο μέσω του αξιόπιστου παγκόσμιου δικτύου μας.", cta: "Δείτε Διαθέσιμα Ζώα" },
  common: { learnMore: "Μάθετε Περισσότερα", getStarted: "Ξεκινήστε", submit: "Υποβολή", cancel: "Ακύρωση", save: "Αποθήκευση", delete: "Διαγραφή", edit: "Επεξεργασία", close: "Κλείσιμο", loading: "Φόρτωση...", error: "Κάτι πήγε στραβά", success: "Επιτυχία", viewAll: "Προβολή Όλων", readMore: "Διαβάστε Περισσότερα", back: "Πίσω", next: "Επόμενο", previous: "Προηγούμενο", search: "Αναζήτηση", filter: "Φίλτρο", sort: "Ταξινόμηση", noResults: "Δεν βρέθηκαν αποτελέσματα" },
  pets: { available: "Διαθέσιμο", pending: "Σε Αναμονή", adopted: "Υιοθετημένο", age: "Ηλικία", breed: "Ράτσα", gender: "Φύλο", size: "Μέγεθος", location: "Τοποθεσία", adoptionFee: "Τέλος Υιοθεσίας", vaccinated: "Εμβολιασμένο", neutered: "Στειρωμένο", microchipped: "Με Μικροτσίπ", goodWithKids: "Καλό με Παιδιά", goodWithPets: "Καλό με Ζώα", houseTrained: "Εκπαιδευμένο", addToCart: "Προσθήκη στο Καλάθι", reserveNow: "Κράτηση Τώρα", description: "Περιγραφή", healthInfo: "Πληροφορίες Υγείας", deliveryInfo: "Πληροφορίες Παράδοσης" },
  delivery: { title: "Επιλογές Παράδοσης", subtitle: "Παγκόσμια μεταφορά κατοικιδίων με δυναμική τιμολόγηση βάσει απόστασης", groundTransport: "Χερσαία Μεταφορά", airCargo: "Αεροπορικό Φορτίο", flightCompanion: "Συνοδός Πτήσης", companion: "Συνοδός", distanceBased: "Τιμή βάσει Απόστασης", estimatedDuration: "Εκτιμώμενη Διάρκεια", safetyCompliance: "Ασφάλεια & Συμμόρφωση" },
  about: { title: "Σχετικά με PawsFam", subtitle: "Το Παγκόσμιο Δίκτυό μας", howItWorks: "Πώς Λειτουργεί", ourCommitment: "Η Δέσμευσή μας" },
  footer: { rights: "Με επιφύλαξη παντός δικαιώματος.", privacy: "Πολιτική Απορρήτου", terms: "Όροι και Προϋποθέσεις" },
  auth: { signIn: "Σύνδεση", signUp: "Εγγραφή", email: "Email", password: "Κωδικός", forgotPassword: "Ξεχάσατε τον κωδικό;", noAccount: "Δεν έχετε λογαριασμό;", hasAccount: "Έχετε ήδη λογαριασμό;" },
  checkout: { title: "Πληρωμή", orderSummary: "Σύνοψη Παραγγελίας", paymentMethod: "Μέθοδος Πληρωμής", placeOrder: "Υποβολή Παραγγελίας", total: "Σύνολο" },
};
export default el;
