const hi = {
  nav: { home: "होम", adopt: "गोद लें", reviews: "समीक्षाएं", foster: "अस्थायी देखभाल", donate: "दान करें", about: "हमारे बारे में", breeds: "नस्लें", catBreeds: "बिल्ली की नस्लें", dogBreeds: "कुत्ते की नस्लें", more: "और", deliveryOptions: "डिलीवरी विकल्प", healthGuarantee: "स्वास्थ्य गारंटी", emotionalSupport: "भावनात्मक सहायता", contact: "संपर्क", startAdopting: "गोद लेना शुरू करें", signIn: "साइन इन", signOut: "साइन आउट", admin: "व्यवस्थापक", orders: "ऑर्डर", orderHistory: "ऑर्डर इतिहास", account: "खाता सेटिंग्स", adminDashboard: "व्यवस्थापक पैनल", cart: "कार्ट", language: "भाषा", currency: "मुद्रा", shoppingCart: "शॉपिंग कार्ट", item: "आइटम", items: "आइटम", cartEmpty: "आपका कार्ट खाली है", browsePets: "पालतू जानवर देखें", subtotal: "उप-योग", proceedToCheckout: "भुगतान करें", moreItems: "+{{count}} और आइटम", moreItems_plural: "+{{count}} और आइटम", deposit: "30% जमा", fullAdoption: "पूर्ण गोद लेना" },
  hero: { title: "अपना आदर्श साथी खोजें", subtitle: "हम अपने विश्वसनीय वैश्विक नेटवर्क के माध्यम से प्यारे परिवारों को दुनिया भर के पालतू जानवरों से जोड़ते हैं।", cta: "उपलब्ध पालतू जानवर देखें" },
  common: { learnMore: "और जानें", getStarted: "शुरू करें", submit: "भेजें", cancel: "रद्द करें", save: "सहेजें", delete: "हटाएं", edit: "संपादित करें", close: "बंद करें", loading: "लोड हो रहा है...", error: "कुछ गलत हो गया", success: "सफल", viewAll: "सभी देखें", readMore: "और पढ़ें", back: "वापस", next: "अगला", previous: "पिछला", search: "खोजें", filter: "फ़िल्टर", sort: "क्रमबद्ध करें", noResults: "कोई परिणाम नहीं" },
  pets: { available: "उपलब्ध", pending: "लंबित", adopted: "गोद लिया गया", age: "उम्र", breed: "नस्ल", gender: "लिंग", size: "आकार", location: "स्थान", adoptionFee: "गोद लेने का शुल्क", vaccinated: "टीकाकृत", neutered: "नपुंसकित", microchipped: "माइक्रोचिप्ड", goodWithKids: "बच्चों के साथ अच्छा", goodWithPets: "जानवरों के साथ अच्छा", houseTrained: "प्रशिक्षित", addToCart: "कार्ट में डालें", reserveNow: "अभी आरक्षित करें", description: "विवरण", healthInfo: "स्वास्थ्य जानकारी", deliveryInfo: "डिलीवरी जानकारी" },
  delivery: { title: "डिलीवरी विकल्प", subtitle: "दूरी-आधारित गतिशील मूल्य निर्धारण के साथ विश्वव्यापी पालतू जानवर परिवहन", groundTransport: "जमीनी परिवहन", airCargo: "हवाई कार्गो", flightCompanion: "फ्लाइट साथी", companion: "साथी", distanceBased: "दूरी-आधारित मूल्य", estimatedDuration: "अनुमानित अवधि", safetyCompliance: "सुरक्षा और अनुपालन" },
  about: { title: "PawsFam के बारे में", subtitle: "हमारा वैश्विक नेटवर्क", howItWorks: "कैसे काम करता है", ourCommitment: "हमारी प्रतिबद्धता" },
  footer: { rights: "सर्वाधिकार सुरक्षित।", privacy: "गोपनीयता नीति", terms: "नियम और शर्तें" },
  auth: { signIn: "साइन इन", signUp: "साइन अप", email: "ईमेल", password: "पासवर्ड", forgotPassword: "पासवर्ड भूल गए?", noAccount: "खाता नहीं है?", hasAccount: "पहले से खाता है?" },
  checkout: { title: "भुगतान", orderSummary: "ऑर्डर सारांश", paymentMethod: "भुगतान विधि", placeOrder: "ऑर्डर करें", total: "कुल" },
};
export default hi;
