const id = {
  nav: { home: "Beranda", adopt: "Adopsi", reviews: "Ulasan", foster: "Titipan", donate: "Donasi", about: "Tentang Kami", breeds: "Ras", catBreeds: "Ras Kucing", dogBreeds: "Ras Anjing", more: "Lainnya", deliveryOptions: "Opsi Pengiriman", healthGuarantee: "Jaminan Kesehatan", emotionalSupport: "Dukungan Emosional", contact: "Kontak", startAdopting: "Mulai Adopsi", signIn: "Masuk", signOut: "Keluar", admin: "Admin", orders: "Pesanan", orderHistory: "Riwayat Pesanan", account: "Pengaturan Akun", adminDashboard: "Dashboard Admin", cart: "Keranjang", language: "Bahasa", currency: "Mata Uang", shoppingCart: "Keranjang Belanja", item: "barang", items: "barang", cartEmpty: "Keranjang Anda kosong", browsePets: "Lihat Hewan", subtotal: "Subtotal", proceedToCheckout: "Lanjut ke Pembayaran", moreItems: "+{{count}} barang lagi", moreItems_plural: "+{{count}} barang lagi", deposit: "DP 30%", fullAdoption: "Adopsi Penuh" },
  hero: { title: "Temukan Teman Sempurna Anda", subtitle: "Kami menghubungkan keluarga penyayang dengan hewan peliharaan di seluruh dunia melalui jaringan global tepercaya kami.", cta: "Lihat Hewan Tersedia" },
  common: { learnMore: "Pelajari Lebih", getStarted: "Mulai", submit: "Kirim", cancel: "Batal", save: "Simpan", delete: "Hapus", edit: "Edit", close: "Tutup", loading: "Memuat...", error: "Terjadi kesalahan", success: "Berhasil", viewAll: "Lihat Semua", readMore: "Baca Selengkapnya", back: "Kembali", next: "Berikutnya", previous: "Sebelumnya", search: "Cari", filter: "Filter", sort: "Urutkan", noResults: "Tidak ada hasil" },
  pets: { available: "Tersedia", pending: "Menunggu", adopted: "Diadopsi", age: "Umur", breed: "Ras", gender: "Jenis Kelamin", size: "Ukuran", location: "Lokasi", adoptionFee: "Biaya Adopsi", vaccinated: "Divaksinasi", neutered: "Disterilkan", microchipped: "Microchip", goodWithKids: "Baik dengan Anak", goodWithPets: "Baik dengan Hewan", houseTrained: "Terlatih", addToCart: "Masukkan Keranjang", reserveNow: "Reservasi Sekarang", description: "Deskripsi", healthInfo: "Info Kesehatan", deliveryInfo: "Info Pengiriman" },
  delivery: { title: "Opsi Pengiriman", subtitle: "Transportasi hewan peliharaan ke seluruh dunia dengan harga dinamis berbasis jarak", groundTransport: "Transportasi Darat", airCargo: "Kargo Udara", flightCompanion: "Pendamping Penerbangan", companion: "Pendamping", distanceBased: "Harga Berbasis Jarak", estimatedDuration: "Perkiraan Waktu", safetyCompliance: "Keamanan & Kepatuhan" },
  about: { title: "Tentang PawsFam", subtitle: "Jaringan Global Kami", howItWorks: "Cara Kerja", ourCommitment: "Komitmen Kami" },
  footer: { rights: "Hak cipta dilindungi.", privacy: "Kebijakan Privasi", terms: "Syarat & Ketentuan" },
  auth: { signIn: "Masuk", signUp: "Daftar", email: "Email", password: "Kata Sandi", forgotPassword: "Lupa kata sandi?", noAccount: "Belum punya akun?", hasAccount: "Sudah punya akun?" },
  checkout: { title: "Pembayaran", orderSummary: "Ringkasan Pesanan", paymentMethod: "Metode Pembayaran", placeOrder: "Buat Pesanan", total: "Total" },
};
export default id;
