const it = {
  nav: { home: "Home", adopt: "Adotta", reviews: "Recensioni", foster: "Affido", donate: "Dona", about: "Chi Siamo", breeds: "Razze", catBreeds: "Razze di Gatti", dogBreeds: "Razze di Cani", more: "Altro", deliveryOptions: "Opzioni di Consegna", healthGuarantee: "Garanzia Salute", emotionalSupport: "Supporto Emotivo", contact: "Contatti", startAdopting: "Inizia ad Adottare", signIn: "Accedi", signOut: "Esci", admin: "Admin", orders: "Ordini", orderHistory: "Storico Ordini", account: "Impostazioni Account", adminDashboard: "Dashboard Admin", cart: "Carrello", language: "Lingua", currency: "Valuta", shoppingCart: "Carrello", item: "articolo", items: "articoli", cartEmpty: "Il carrello è vuoto", browsePets: "Sfoglia Animali", subtotal: "Subtotale", proceedToCheckout: "Vai al Pagamento", moreItems: "+{{count}} altro articolo", moreItems_plural: "+{{count}} altri articoli", deposit: "Acconto 30%", fullAdoption: "Adozione Completa" },
  hero: { title: "Trova il tuo Compagno Perfetto", subtitle: "Colleghiamo famiglie amorevoli con animali in tutto il mondo attraverso la nostra rete globale affidabile.", cta: "Vedi Animali Disponibili" },
  common: { learnMore: "Scopri di Più", getStarted: "Inizia", submit: "Invia", cancel: "Annulla", save: "Salva", delete: "Elimina", edit: "Modifica", close: "Chiudi", loading: "Caricamento...", error: "Qualcosa è andato storto", success: "Successo", viewAll: "Vedi Tutto", readMore: "Leggi di Più", back: "Indietro", next: "Avanti", previous: "Precedente", search: "Cerca", filter: "Filtra", sort: "Ordina", noResults: "Nessun risultato" },
  pets: { available: "Disponibile", pending: "In Attesa", adopted: "Adottato", age: "Età", breed: "Razza", gender: "Sesso", size: "Taglia", location: "Posizione", adoptionFee: "Tassa di Adozione", vaccinated: "Vaccinato", neutered: "Sterilizzato", microchipped: "Microchippato", goodWithKids: "Buono con Bambini", goodWithPets: "Buono con Animali", houseTrained: "Addestrato", addToCart: "Aggiungi al Carrello", reserveNow: "Prenota Ora", description: "Descrizione", healthInfo: "Info Salute", deliveryInfo: "Info Consegna" },
  delivery: { title: "Opzioni di Consegna", subtitle: "Trasporto animali mondiale con prezzi dinamici basati sulla distanza", groundTransport: "Trasporto Terrestre", airCargo: "Cargo Aereo", flightCompanion: "Accompagnatore in Volo", companion: "Accompagnatore", distanceBased: "Prezzo per Distanza", estimatedDuration: "Durata Stimata", safetyCompliance: "Sicurezza e Conformità" },
  about: { title: "Chi è PawsFam", subtitle: "La Nostra Rete Globale", howItWorks: "Come Funziona", ourCommitment: "Il Nostro Impegno" },
  footer: { rights: "Tutti i diritti riservati.", privacy: "Privacy", terms: "Termini e Condizioni" },
  auth: { signIn: "Accedi", signUp: "Registrati", email: "Email", password: "Password", forgotPassword: "Password dimenticata?", noAccount: "Non hai un account?", hasAccount: "Hai già un account?" },
  checkout: { title: "Pagamento", orderSummary: "Riepilogo Ordine", paymentMethod: "Metodo di Pagamento", placeOrder: "Ordina", total: "Totale" },
};
export default it;
