const nl = {
  nav: { home: "Home", adopt: "Adopteer", reviews: "Beoordelingen", foster: "Pleegzorg", donate: "Doneer", about: "Over Ons", breeds: "Rassen", catBreeds: "Kattenrassen", dogBreeds: "Hondenrassen", more: "Meer", deliveryOptions: "Bezorgopties", healthGuarantee: "Gezondheidsgarantie", emotionalSupport: "Emotionele Steun", contact: "Contact", startAdopting: "Begin met Adopteren", signIn: "Inloggen", signOut: "Uitloggen", admin: "Admin", orders: "Bestellingen", orderHistory: "Bestelgeschiedenis", account: "Accountinstellingen", adminDashboard: "Admin Dashboard", cart: "Winkelwagen", language: "Taal", currency: "Valuta", shoppingCart: "Winkelwagen", item: "artikel", items: "artikelen", cartEmpty: "Je winkelwagen is leeg", browsePets: "Huisdieren Bekijken", subtotal: "Subtotaal", proceedToCheckout: "Naar Afrekenen", moreItems: "+{{count}} artikel meer", moreItems_plural: "+{{count}} artikelen meer", deposit: "30% Aanbetaling", fullAdoption: "Volledige Adoptie" },
  hero: { title: "Vind Je Perfecte Metgezel", subtitle: "We verbinden liefdevolle gezinnen met huisdieren over de hele wereld via ons betrouwbare wereldwijde netwerk.", cta: "Beschikbare Huisdieren Bekijken" },
  common: { learnMore: "Meer Info", getStarted: "Aan de Slag", submit: "Verzenden", cancel: "Annuleren", save: "Opslaan", delete: "Verwijderen", edit: "Bewerken", close: "Sluiten", loading: "Laden...", error: "Er ging iets mis", success: "Gelukt", viewAll: "Alles Bekijken", readMore: "Lees Meer", back: "Terug", next: "Volgende", previous: "Vorige", search: "Zoeken", filter: "Filter", sort: "Sorteren", noResults: "Geen resultaten" },
  pets: { available: "Beschikbaar", pending: "In Behandeling", adopted: "Geadopteerd", age: "Leeftijd", breed: "Ras", gender: "Geslacht", size: "Grootte", location: "Locatie", adoptionFee: "Adoptiekosten", vaccinated: "Gevaccineerd", neutered: "Gecastreerd", microchipped: "Gechipt", goodWithKids: "Goed met Kinderen", goodWithPets: "Goed met Dieren", houseTrained: "Zindelijk", addToCart: "In Winkelwagen", reserveNow: "Nu Reserveren", description: "Beschrijving", healthInfo: "Gezondheidsinfo", deliveryInfo: "Bezorginfo" },
  delivery: { title: "Bezorgopties", subtitle: "Wereldwijd dierentransport met dynamische afstandsprijzen", groundTransport: "Grondtransport", airCargo: "Luchtvracht", flightCompanion: "Vluchtbegeleider", companion: "Begeleider", distanceBased: "Afstandsprijs", estimatedDuration: "Geschatte Duur", safetyCompliance: "Veiligheid & Naleving" },
  about: { title: "Over PawsFam", subtitle: "Ons Wereldwijde Netwerk", howItWorks: "Hoe Het Werkt", ourCommitment: "Onze Belofte" },
  footer: { rights: "Alle rechten voorbehouden.", privacy: "Privacybeleid", terms: "Algemene Voorwaarden" },
  auth: { signIn: "Inloggen", signUp: "Registreren", email: "E-mail", password: "Wachtwoord", forgotPassword: "Wachtwoord vergeten?", noAccount: "Geen account?", hasAccount: "Al een account?" },
  checkout: { title: "Afrekenen", orderSummary: "Besteloverzicht", paymentMethod: "Betaalmethode", placeOrder: "Bestelling Plaatsen", total: "Totaal" },
};
export default nl;
