const pl = {
  nav: { home: "Strona Główna", adopt: "Adoptuj", reviews: "Opinie", foster: "Dom Tymczasowy", donate: "Wpłać", about: "O Nas", breeds: "Rasy", catBreeds: "Rasy Kotów", dogBreeds: "Rasy Psów", more: "Więcej", deliveryOptions: "Opcje Dostawy", healthGuarantee: "Gwarancja Zdrowia", emotionalSupport: "Wsparcie Emocjonalne", contact: "Kontakt", startAdopting: "Zacznij Adoptować", signIn: "Zaloguj się", signOut: "Wyloguj się", admin: "Admin", orders: "Zamówienia", orderHistory: "Historia Zamówień", account: "Ustawienia Konta", adminDashboard: "Panel Admina", cart: "Koszyk", language: "Język", currency: "Waluta", shoppingCart: "Koszyk", item: "produkt", items: "produktów", cartEmpty: "Koszyk jest pusty", browsePets: "Przeglądaj Zwierzęta", subtotal: "Suma", proceedToCheckout: "Przejdź do Płatności", moreItems: "+{{count}} więcej", moreItems_plural: "+{{count}} więcej", deposit: "Zaliczka 30%", fullAdoption: "Pełna Adopcja" },
  hero: { title: "Znajdź Idealnego Towarzysza", subtitle: "Łączymy kochające rodziny ze zwierzętami z całego świata dzięki naszej zaufanej globalnej sieci.", cta: "Zobacz Dostępne Zwierzęta" },
  common: { learnMore: "Dowiedz się Więcej", getStarted: "Rozpocznij", submit: "Wyślij", cancel: "Anuluj", save: "Zapisz", delete: "Usuń", edit: "Edytuj", close: "Zamknij", loading: "Ładowanie...", error: "Coś poszło nie tak", success: "Sukces", viewAll: "Zobacz Wszystko", readMore: "Czytaj Więcej", back: "Wstecz", next: "Dalej", previous: "Poprzedni", search: "Szukaj", filter: "Filtruj", sort: "Sortuj", noResults: "Brak wyników" },
  pets: { available: "Dostępny", pending: "Oczekujący", adopted: "Adoptowany", age: "Wiek", breed: "Rasa", gender: "Płeć", size: "Rozmiar", location: "Lokalizacja", adoptionFee: "Opłata Adopcyjna", vaccinated: "Zaszczepiony", neutered: "Wykastrowany", microchipped: "Zaczipowany", goodWithKids: "Dobry z Dziećmi", goodWithPets: "Dobry z Zwierzętami", houseTrained: "Wytrenowany", addToCart: "Dodaj do Koszyka", reserveNow: "Zarezerwuj", description: "Opis", healthInfo: "Informacje Zdrowotne", deliveryInfo: "Informacje o Dostawie" },
  delivery: { title: "Opcje Dostawy", subtitle: "Światowy transport zwierząt z dynamicznymi cenami opartymi na odległości", groundTransport: "Transport Lądowy", airCargo: "Cargo Lotnicze", flightCompanion: "Towarzysz Lotu", companion: "Towarzysz", distanceBased: "Cena wg Odległości", estimatedDuration: "Szacowany Czas", safetyCompliance: "Bezpieczeństwo" },
  about: { title: "O PawsFam", subtitle: "Nasza Globalna Sieć", howItWorks: "Jak to Działa", ourCommitment: "Nasze Zobowiązanie" },
  footer: { rights: "Wszelkie prawa zastrzeżone.", privacy: "Polityka Prywatności", terms: "Regulamin" },
  auth: { signIn: "Zaloguj się", signUp: "Zarejestruj się", email: "E-mail", password: "Hasło", forgotPassword: "Zapomniałeś hasła?", noAccount: "Nie masz konta?", hasAccount: "Masz już konto?" },
  checkout: { title: "Płatność", orderSummary: "Podsumowanie", paymentMethod: "Metoda Płatności", placeOrder: "Złóż Zamówienie", total: "Razem" },
};
export default pl;
