const pt = {
  nav: { home: "Início", adopt: "Adotar", reviews: "Avaliações", foster: "Lar Temporário", donate: "Doar", about: "Sobre", breeds: "Raças", catBreeds: "Raças de Gatos", dogBreeds: "Raças de Cães", more: "Mais", deliveryOptions: "Opções de Entrega", healthGuarantee: "Garantia de Saúde", emotionalSupport: "Apoio Emocional", contact: "Contato", startAdopting: "Comece a Adotar", signIn: "Entrar", signOut: "Sair", admin: "Admin", orders: "Pedidos", orderHistory: "Histórico de Pedidos", account: "Configurações da Conta", adminDashboard: "Painel Admin", cart: "Carrinho", language: "Idioma", currency: "Moeda", shoppingCart: "Carrinho de Compras", item: "item", items: "itens", cartEmpty: "Seu carrinho está vazio", browsePets: "Ver Animais", subtotal: "Subtotal", proceedToCheckout: "Ir para Pagamento", moreItems: "+{{count}} item a mais", moreItems_plural: "+{{count}} itens a mais", deposit: "Depósito 30%", fullAdoption: "Adoção Completa" },
  hero: { title: "Encontre Seu Companheiro Perfeito", subtitle: "Conectamos famílias amorosas com animais de todo o mundo através da nossa rede global confiável.", cta: "Ver Animais Disponíveis" },
  common: { learnMore: "Saiba Mais", getStarted: "Começar", submit: "Enviar", cancel: "Cancelar", save: "Salvar", delete: "Excluir", edit: "Editar", close: "Fechar", loading: "Carregando...", error: "Algo deu errado", success: "Sucesso", viewAll: "Ver Tudo", readMore: "Leia Mais", back: "Voltar", next: "Próximo", previous: "Anterior", search: "Buscar", filter: "Filtrar", sort: "Ordenar", noResults: "Nenhum resultado" },
  pets: { available: "Disponível", pending: "Pendente", adopted: "Adotado", age: "Idade", breed: "Raça", gender: "Gênero", size: "Tamanho", location: "Localização", adoptionFee: "Taxa de Adoção", vaccinated: "Vacinado", neutered: "Castrado", microchipped: "Microchipado", goodWithKids: "Bom com Crianças", goodWithPets: "Bom com Animais", houseTrained: "Treinado", addToCart: "Adicionar ao Carrinho", reserveNow: "Reservar Agora", description: "Descrição", healthInfo: "Info de Saúde", deliveryInfo: "Info de Entrega" },
  delivery: { title: "Opções de Entrega", subtitle: "Transporte mundial de animais com preços dinâmicos baseados em distância", groundTransport: "Transporte Terrestre", airCargo: "Carga Aérea", flightCompanion: "Acompanhante de Voo", companion: "Acompanhante", distanceBased: "Preço por Distância", estimatedDuration: "Duração Estimada", safetyCompliance: "Segurança e Conformidade" },
  about: { title: "Sobre a PawsFam", subtitle: "Nossa Rede Global", howItWorks: "Como Funciona", ourCommitment: "Nosso Compromisso" },
  footer: { rights: "Todos os direitos reservados.", privacy: "Política de Privacidade", terms: "Termos e Condições" },
  auth: { signIn: "Entrar", signUp: "Cadastrar", email: "E-mail", password: "Senha", forgotPassword: "Esqueceu a senha?", noAccount: "Não tem conta?", hasAccount: "Já tem conta?" },
  checkout: { title: "Pagamento", orderSummary: "Resumo do Pedido", paymentMethod: "Método de Pagamento", placeOrder: "Finalizar Pedido", total: "Total" },
};
export default pt;
