const ru = {
  nav: { home: "Главная", adopt: "Взять питомца", reviews: "Отзывы", foster: "Передержка", donate: "Пожертвовать", about: "О нас", breeds: "Породы", catBreeds: "Породы кошек", dogBreeds: "Породы собак", more: "Ещё", deliveryOptions: "Варианты доставки", healthGuarantee: "Гарантия здоровья", emotionalSupport: "Эмоциональная поддержка", contact: "Контакты", startAdopting: "Начать усыновление", signIn: "Войти", signOut: "Выйти", admin: "Админ", orders: "Заказы", orderHistory: "История заказов", account: "Настройки аккаунта", adminDashboard: "Панель управления", cart: "Корзина", language: "Язык", currency: "Валюта", shoppingCart: "Корзина покупок", item: "товар", items: "товаров", cartEmpty: "Корзина пуста", browsePets: "Смотреть питомцев", subtotal: "Итого", proceedToCheckout: "Перейти к оплате", moreItems: "+{{count}} ещё", moreItems_plural: "+{{count}} ещё", deposit: "Залог 30%", fullAdoption: "Полное усыновление" },
  hero: { title: "Найдите идеального компаньона", subtitle: "Мы соединяем любящие семьи с питомцами по всему миру через нашу надёжную глобальную сеть.", cta: "Смотреть доступных питомцев" },
  common: { learnMore: "Узнать больше", getStarted: "Начать", submit: "Отправить", cancel: "Отмена", save: "Сохранить", delete: "Удалить", edit: "Редактировать", close: "Закрыть", loading: "Загрузка...", error: "Что-то пошло не так", success: "Успех", viewAll: "Показать все", readMore: "Читать далее", back: "Назад", next: "Далее", previous: "Назад", search: "Поиск", filter: "Фильтр", sort: "Сортировка", noResults: "Ничего не найдено" },
  pets: { available: "Доступен", pending: "Ожидание", adopted: "Усыновлён", age: "Возраст", breed: "Порода", gender: "Пол", size: "Размер", location: "Местоположение", adoptionFee: "Плата за усыновление", vaccinated: "Вакцинирован", neutered: "Кастрирован", microchipped: "Чипирован", goodWithKids: "Ладит с детьми", goodWithPets: "Ладит с животными", houseTrained: "Приучен к дому", addToCart: "В корзину", reserveNow: "Забронировать", description: "Описание", healthInfo: "Здоровье", deliveryInfo: "Доставка" },
  delivery: { title: "Варианты доставки", subtitle: "Мировая транспортировка питомцев с динамическим ценообразованием по расстоянию", groundTransport: "Наземный транспорт", airCargo: "Авиагруз", flightCompanion: "Сопровождающий на борту", companion: "Сопровождающий", distanceBased: "Цена по расстоянию", estimatedDuration: "Примерное время", safetyCompliance: "Безопасность" },
  about: { title: "О PawsFam", subtitle: "Наша глобальная сеть", howItWorks: "Как это работает", ourCommitment: "Наши обязательства" },
  footer: { rights: "Все права защищены.", privacy: "Политика конфиденциальности", terms: "Условия использования" },
  auth: { signIn: "Войти", signUp: "Регистрация", email: "Эл. почта", password: "Пароль", forgotPassword: "Забыли пароль?", noAccount: "Нет аккаунта?", hasAccount: "Уже есть аккаунт?" },
  checkout: { title: "Оформление", orderSummary: "Итого заказа", paymentMethod: "Способ оплаты", placeOrder: "Оформить заказ", total: "Итого" },
};
export default ru;
