const sv = {
  nav: { home: "Hem", adopt: "Adoptera", reviews: "Recensioner", foster: "Fosterhem", donate: "Donera", about: "Om Oss", breeds: "Raser", catBreeds: "Kattraser", dogBreeds: "Hundraser", more: "Mer", deliveryOptions: "Leveransalternativ", healthGuarantee: "Hälsogaranti", emotionalSupport: "Emotionellt Stöd", contact: "Kontakt", startAdopting: "Börja Adoptera", signIn: "Logga In", signOut: "Logga Ut", admin: "Admin", orders: "Beställningar", orderHistory: "Orderhistorik", account: "Kontoinställningar", adminDashboard: "Admin Panel", cart: "Kundvagn", language: "Språk", currency: "Valuta", shoppingCart: "Kundvagn", item: "artikel", items: "artiklar", cartEmpty: "Din kundvagn är tom", browsePets: "Bläddra Djur", subtotal: "Delsumma", proceedToCheckout: "Till Kassan", moreItems: "+{{count}} artikel till", moreItems_plural: "+{{count}} artiklar till", deposit: "30% Handpenning", fullAdoption: "Full Adoption" },
  hero: { title: "Hitta Din Perfekta Kompanjon", subtitle: "Vi kopplar samman kärleksfulla familjer med husdjur världen över genom vårt pålitliga globala nätverk.", cta: "Se Tillgängliga Djur" },
  common: { learnMore: "Läs Mer", getStarted: "Kom Igång", submit: "Skicka", cancel: "Avbryt", save: "Spara", delete: "Radera", edit: "Redigera", close: "Stäng", loading: "Laddar...", error: "Något gick fel", success: "Lyckades", viewAll: "Visa Alla", readMore: "Läs Mer", back: "Tillbaka", next: "Nästa", previous: "Föregående", search: "Sök", filter: "Filtrera", sort: "Sortera", noResults: "Inga resultat" },
  pets: { available: "Tillgänglig", pending: "Väntande", adopted: "Adopterad", age: "Ålder", breed: "Ras", gender: "Kön", size: "Storlek", location: "Plats", adoptionFee: "Adoptionsavgift", vaccinated: "Vaccinerad", neutered: "Kastrerad", microchipped: "Mikrochippad", goodWithKids: "Bra med Barn", goodWithPets: "Bra med Djur", houseTrained: "Rumsren", addToCart: "Lägg i Kundvagn", reserveNow: "Reservera Nu", description: "Beskrivning", healthInfo: "Hälsoinformation", deliveryInfo: "Leveransinfo" },
  delivery: { title: "Leveransalternativ", subtitle: "Världsomfattande djurtransport med dynamisk avståndsprissättning", groundTransport: "Marktransport", airCargo: "Flygfrakt", flightCompanion: "Flygfölje", companion: "Följeslagare", distanceBased: "Avståndspris", estimatedDuration: "Beräknad Tid", safetyCompliance: "Säkerhet & Efterlevnad" },
  about: { title: "Om PawsFam", subtitle: "Vårt Globala Nätverk", howItWorks: "Så Fungerar Det", ourCommitment: "Vårt Löfte" },
  footer: { rights: "Alla rättigheter förbehållna.", privacy: "Integritetspolicy", terms: "Villkor" },
  auth: { signIn: "Logga In", signUp: "Registrera", email: "E-post", password: "Lösenord", forgotPassword: "Glömt lösenord?", noAccount: "Inget konto?", hasAccount: "Har du redan konto?" },
  checkout: { title: "Kassa", orderSummary: "Ordersammanfattning", paymentMethod: "Betalningsmetod", placeOrder: "Lägg Beställning", total: "Totalt" },
};
export default sv;
