const th = {
  nav: { home: "หน้าหลัก", adopt: "รับเลี้ยง", reviews: "รีวิว", foster: "อุปถัมภ์", donate: "บริจาค", about: "เกี่ยวกับเรา", breeds: "สายพันธุ์", catBreeds: "สายพันธุ์แมว", dogBreeds: "สายพันธุ์สุนัข", more: "เพิ่มเติม", deliveryOptions: "ตัวเลือกการจัดส่ง", healthGuarantee: "รับประกันสุขภาพ", emotionalSupport: "การสนับสนุนทางอารมณ์", contact: "ติดต่อ", startAdopting: "เริ่มรับเลี้ยง", signIn: "เข้าสู่ระบบ", signOut: "ออกจากระบบ", admin: "ผู้ดูแล", orders: "คำสั่งซื้อ", orderHistory: "ประวัติคำสั่งซื้อ", account: "ตั้งค่าบัญชี", adminDashboard: "แดชบอร์ดผู้ดูแล", cart: "ตะกร้า", language: "ภาษา", currency: "สกุลเงิน", shoppingCart: "ตะกร้าสินค้า", item: "รายการ", items: "รายการ", cartEmpty: "ตะกร้าของคุณว่างเปล่า", browsePets: "ดูสัตว์เลี้ยง", subtotal: "ยอดรวมย่อย", proceedToCheckout: "ดำเนินการชำระเงิน", moreItems: "+{{count}} รายการเพิ่มเติม", moreItems_plural: "+{{count}} รายการเพิ่มเติม", deposit: "มัดจำ 30%", fullAdoption: "รับเลี้ยงเต็มจำนวน" },
  hero: { title: "ค้นหาเพื่อนคู่ใจของคุณ", subtitle: "เราเชื่อมต่อครอบครัวที่รักกับสัตว์เลี้ยงทั่วโลกผ่านเครือข่ายที่เชื่อถือได้ของเรา", cta: "ดูสัตว์เลี้ยงที่มี" },
  common: { learnMore: "เรียนรู้เพิ่มเติม", getStarted: "เริ่มต้น", submit: "ส่ง", cancel: "ยกเลิก", save: "บันทึก", delete: "ลบ", edit: "แก้ไข", close: "ปิด", loading: "กำลังโหลด...", error: "เกิดข้อผิดพลาด", success: "สำเร็จ", viewAll: "ดูทั้งหมด", readMore: "อ่านต่อ", back: "กลับ", next: "ถัดไป", previous: "ก่อนหน้า", search: "ค้นหา", filter: "กรอง", sort: "จัดเรียง", noResults: "ไม่พบผลลัพธ์" },
  pets: { available: "พร้อมรับเลี้ยง", pending: "รอดำเนินการ", adopted: "รับเลี้ยงแล้ว", age: "อายุ", breed: "สายพันธุ์", gender: "เพศ", size: "ขนาด", location: "ที่ตั้ง", adoptionFee: "ค่าธรรมเนียม", vaccinated: "ฉีดวัคซีนแล้ว", neutered: "ทำหมันแล้ว", microchipped: "ฝังไมโครชิป", goodWithKids: "ดีกับเด็ก", goodWithPets: "ดีกับสัตว์อื่น", houseTrained: "ฝึกแล้ว", addToCart: "เพิ่มลงตะกร้า", reserveNow: "จองเลย", description: "รายละเอียด", healthInfo: "ข้อมูลสุขภาพ", deliveryInfo: "ข้อมูลจัดส่ง" },
  delivery: { title: "ตัวเลือกการจัดส่ง", subtitle: "การขนส่งสัตว์เลี้ยงทั่วโลกด้วยราคาแบบไดนามิกตามระยะทาง", groundTransport: "ขนส่งทางบก", airCargo: "สินค้าทางอากาศ", flightCompanion: "ผู้ดูแลบนเครื่อง", companion: "ผู้ดูแล", distanceBased: "ราคาตามระยะทาง", estimatedDuration: "ระยะเวลาโดยประมาณ", safetyCompliance: "ความปลอดภัยและการปฏิบัติตาม" },
  about: { title: "เกี่ยวกับ PawsFam", subtitle: "เครือข่ายทั่วโลกของเรา", howItWorks: "วิธีการทำงาน", ourCommitment: "คำมั่นสัญญาของเรา" },
  footer: { rights: "สงวนลิขสิทธิ์", privacy: "นโยบายความเป็นส่วนตัว", terms: "ข้อกำหนดและเงื่อนไข" },
  auth: { signIn: "เข้าสู่ระบบ", signUp: "สมัครสมาชิก", email: "อีเมล", password: "รหัสผ่าน", forgotPassword: "ลืมรหัสผ่าน?", noAccount: "ยังไม่มีบัญชี?", hasAccount: "มีบัญชีแล้ว?" },
  checkout: { title: "ชำระเงิน", orderSummary: "สรุปคำสั่งซื้อ", paymentMethod: "วิธีชำระเงิน", placeOrder: "สั่งซื้อ", total: "รวม" },
};
export default th;
