const tr = {
  nav: { home: "Ana Sayfa", adopt: "Sahiplen", reviews: "Yorumlar", foster: "Geçici Bakım", donate: "Bağış Yap", about: "Hakkımızda", breeds: "Irklar", catBreeds: "Kedi Irkları", dogBreeds: "Köpek Irkları", more: "Daha Fazla", deliveryOptions: "Teslimat Seçenekleri", healthGuarantee: "Sağlık Garantisi", emotionalSupport: "Duygusal Destek", contact: "İletişim", startAdopting: "Sahiplenmeye Başla", signIn: "Giriş Yap", signOut: "Çıkış Yap", admin: "Yönetici", orders: "Siparişler", orderHistory: "Sipariş Geçmişi", account: "Hesap Ayarları", adminDashboard: "Yönetim Paneli", cart: "Sepet", language: "Dil", currency: "Para Birimi", shoppingCart: "Alışveriş Sepeti", item: "ürün", items: "ürün", cartEmpty: "Sepetiniz boş", browsePets: "Hayvanları İncele", subtotal: "Ara Toplam", proceedToCheckout: "Ödemeye Geç", moreItems: "+{{count}} ürün daha", moreItems_plural: "+{{count}} ürün daha", deposit: "%30 Depozito", fullAdoption: "Tam Sahiplenme" },
  hero: { title: "Mükemmel Arkadaşınızı Bulun", subtitle: "Güvenilir küresel ağımız aracılığıyla sevgi dolu aileleri dünya genelindeki evcil hayvanlarla buluşturuyoruz.", cta: "Mevcut Hayvanları Gör" },
  common: { learnMore: "Daha Fazla Bilgi", getStarted: "Başla", submit: "Gönder", cancel: "İptal", save: "Kaydet", delete: "Sil", edit: "Düzenle", close: "Kapat", loading: "Yükleniyor...", error: "Bir hata oluştu", success: "Başarılı", viewAll: "Tümünü Gör", readMore: "Devamını Oku", back: "Geri", next: "İleri", previous: "Önceki", search: "Ara", filter: "Filtrele", sort: "Sırala", noResults: "Sonuç bulunamadı" },
  pets: { available: "Mevcut", pending: "Beklemede", adopted: "Sahiplenildi", age: "Yaş", breed: "Irk", gender: "Cinsiyet", size: "Boyut", location: "Konum", adoptionFee: "Sahiplenme Ücreti", vaccinated: "Aşılı", neutered: "Kısırlaştırılmış", microchipped: "Çipli", goodWithKids: "Çocuklarla İyi", goodWithPets: "Hayvanlarla İyi", houseTrained: "Eğitimli", addToCart: "Sepete Ekle", reserveNow: "Şimdi Rezerve Et", description: "Açıklama", healthInfo: "Sağlık Bilgisi", deliveryInfo: "Teslimat Bilgisi" },
  delivery: { title: "Teslimat Seçenekleri", subtitle: "Mesafeye dayalı dinamik fiyatlandırma ile dünya çapında evcil hayvan taşımacılığı", groundTransport: "Kara Taşımacılığı", airCargo: "Hava Kargo", flightCompanion: "Uçuş Eşlikçisi", companion: "Eşlikçi", distanceBased: "Mesafeye Dayalı Fiyat", estimatedDuration: "Tahmini Süre", safetyCompliance: "Güvenlik ve Uyumluluk" },
  about: { title: "PawsFam Hakkında", subtitle: "Küresel Ağımız", howItWorks: "Nasıl Çalışır", ourCommitment: "Taahhüdümüz" },
  footer: { rights: "Tüm hakları saklıdır.", privacy: "Gizlilik Politikası", terms: "Şartlar ve Koşullar" },
  auth: { signIn: "Giriş Yap", signUp: "Kayıt Ol", email: "E-posta", password: "Şifre", forgotPassword: "Şifrenizi mi unuttunuz?", noAccount: "Hesabınız yok mu?", hasAccount: "Zaten hesabınız var mı?" },
  checkout: { title: "Ödeme", orderSummary: "Sipariş Özeti", paymentMethod: "Ödeme Yöntemi", placeOrder: "Sipariş Ver", total: "Toplam" },
};
export default tr;
