const uk = {
  nav: { home: "Головна", adopt: "Прихистити", reviews: "Відгуки", foster: "Тимчасовий дім", donate: "Пожертвувати", about: "Про нас", breeds: "Породи", catBreeds: "Породи котів", dogBreeds: "Породи собак", more: "Більше", deliveryOptions: "Варіанти доставки", healthGuarantee: "Гарантія здоров'я", emotionalSupport: "Емоційна підтримка", contact: "Контакти", startAdopting: "Почати прихищення", signIn: "Увійти", signOut: "Вийти", admin: "Адмін", orders: "Замовлення", orderHistory: "Історія замовлень", account: "Налаштування акаунту", adminDashboard: "Панель управління", cart: "Кошик", language: "Мова", currency: "Валюта", shoppingCart: "Кошик", item: "товар", items: "товарів", cartEmpty: "Кошик порожній", browsePets: "Переглянути тварин", subtotal: "Проміжний підсумок", proceedToCheckout: "Перейти до оплати", moreItems: "+{{count}} ще", moreItems_plural: "+{{count}} ще", deposit: "Завдаток 30%", fullAdoption: "Повне прихищення" },
  hero: { title: "Знайдіть свого ідеального компаньйона", subtitle: "Ми з'єднуємо любящі сім'ї з домашніми тваринами по всьому світу через нашу надійну глобальну мережу.", cta: "Переглянути доступних тварин" },
  common: { learnMore: "Дізнатись більше", getStarted: "Почати", submit: "Надіслати", cancel: "Скасувати", save: "Зберегти", delete: "Видалити", edit: "Редагувати", close: "Закрити", loading: "Завантаження...", error: "Щось пішло не так", success: "Успіх", viewAll: "Переглянути все", readMore: "Читати далі", back: "Назад", next: "Далі", previous: "Попередній", search: "Пошук", filter: "Фільтр", sort: "Сортування", noResults: "Нічого не знайдено" },
  pets: { available: "Доступний", pending: "Очікує", adopted: "Прихищений", age: "Вік", breed: "Порода", gender: "Стать", size: "Розмір", location: "Місцезнаходження", adoptionFee: "Плата за прихищення", vaccinated: "Вакцинований", neutered: "Кастрований", microchipped: "Чіпований", goodWithKids: "Добрий з дітьми", goodWithPets: "Добрий з тваринами", houseTrained: "Привчений до дому", addToCart: "До кошика", reserveNow: "Забронювати", description: "Опис", healthInfo: "Інформація про здоров'я", deliveryInfo: "Інформація про доставку" },
  delivery: { title: "Варіанти доставки", subtitle: "Світова транспортування тварин з динамічним ціноутворенням за відстанню", groundTransport: "Наземний транспорт", airCargo: "Авіавантаж", flightCompanion: "Супровідник у літаку", companion: "Супровідник", distanceBased: "Ціна за відстанню", estimatedDuration: "Орієнтовний час", safetyCompliance: "Безпека" },
  about: { title: "Про PawsFam", subtitle: "Наша глобальна мережа", howItWorks: "Як це працює", ourCommitment: "Наші зобов'язання" },
  footer: { rights: "Усі права захищені.", privacy: "Політика конфіденційності", terms: "Умови використання" },
  auth: { signIn: "Увійти", signUp: "Реєстрація", email: "Ел. пошта", password: "Пароль", forgotPassword: "Забули пароль?", noAccount: "Немає акаунту?", hasAccount: "Вже є акаунт?" },
  checkout: { title: "Оформлення", orderSummary: "Підсумок замовлення", paymentMethod: "Спосіб оплати", placeOrder: "Оформити замовлення", total: "Разом" },
};
export default uk;
