const fr = {
  nav: {
    home: "Accueil", adopt: "Adopter", reviews: "Avis", foster: "Famille d'accueil", donate: "Faire un don", about: "À propos", breeds: "Races", catBreeds: "Races de chats", dogBreeds: "Races de chiens", more: "Plus", deliveryOptions: "Options de livraison", healthGuarantee: "Garantie santé", emotionalSupport: "Soutien émotionnel", contact: "Contact", startAdopting: "Commencer l'adoption", admin: "Admin", orders: "Commandes", signOut: "Déconnexion", signIn: "Connexion", accountSettings: "Paramètres du compte", orderHistory: "Historique des commandes", adminDashboard: "Tableau de bord admin", currency: "Devise", cart: "Panier", browsePets: "Parcourir les animaux", shoppingCart: "Panier d'achat", item: "article", items: "articles", yourCartEmpty: "Votre panier est vide", deposit30: "Acompte de 30%", fullAdoption: "Adoption complète", moreItems: "+{{count}} article(s) supplémentaire(s)", subtotal: "Sous-total", proceedToCheckout: "Passer à la caisse",
  },
  hero: {
    badge: "Plus de 5 000 adoptions réussies", title1: "Trouvez votre", titleHighlight: "Compagnon", title2: "Idéal", description: "Chaque animal mérite un foyer aimant. Parcourez des centaines d'adorables animaux en attente de leurs familles pour toujours et faites la différence aujourd'hui.", browsePets: "Parcourir les animaux", learnMore: "En savoir plus", petsAdopted: "Animaux adoptés", verifiedShelters: "Refuges vérifiés", support247: "Support", slideAlt: "Diaporama animaux {{index}}", goToSlide: "Aller à la diapositive {{index}}",
  },
  howItWorks: {
    label: "Processus simple", title: "Comment fonctionne l'adoption", description: "Nous avons rendu le processus d'adoption simple et sans stress. Voici comment ramener votre nouveau meilleur ami à la maison.", step1Title: "Parcourir les animaux", step1Desc: "Explorez notre galerie d'adorables animaux à la recherche de leurs foyers pour toujours.", step2Title: "Postuler en ligne", step2Desc: "Remplissez notre simple demande d'adoption avec vos coordonnées.", step3Title: "Rencontre", step3Desc: "Planifiez une visite pour rencontrer votre potentiel nouveau membre de la famille.", step4Title: "Bienvenue à la maison", step4Desc: "Complétez l'adoption et ramenez votre nouveau compagnon à la maison !",
  },
  featured: {
    label: "Amis en vedette", title: "Des animaux vous attendent", description: "Rencontrez certains de nos adorables animaux prêts à faire partie de votre famille.", viewAllPets: "Voir tous les animaux", justAdded: "Juste ajouté", newArrivals: "Nouvelles arrivées", newArrivalsDesc: "Découvrez les derniers animaux à la recherche de leur foyer pour toujours.", seeAllNewPets: "Voir tous les nouveaux animaux", dogsLabel: "🐕 Chiens", dogsTitle: "Chiens disponibles à l'adoption", dogsDesc: "Trouvez votre compagnon canin idéal parmi notre sélection de chiens adorables.", viewAllDogs: "Voir tous les chiens", catsLabel: "🐈 Chats", catsTitle: "Chats disponibles à l'adoption", catsDesc: "Découvrez des chats doux et joueurs en attente d'un foyer aimant.", viewAllCats: "Voir tous les chats",
  },
  trust: {
    title: "Nous privilégions l'élevage éthique et le bien-être animal", description: "Notre engagement envers l'excellence est soutenu par des organisations de premier plan qui établissent les normes les plus élevées en matière de soins et de pratiques d'élevage.", cfaFull: "Association des amateurs de chats", cfaDesc: "Le plus grand registre mondial de chats de race, établissant la norme pour les races de chats depuis 1906.", ticaFull: "L'Association internationale des chats", ticaDesc: "Le plus grand registre génétique mondial de chats de race et domestiques, promouvant la possession responsable de chats.", usdaFull: "Département de l'Agriculture des États-Unis", usdaDesc: "Agence fédérale de réglementation assurant les normes de bien-être animal et les certifications sanitaires pour le transport des animaux.", certifiedNote: "Tous nos éleveurs sont certifiés et régulièrement inspectés pour garantir les normes de soins les plus élevées.",
  },
  journey: {
    label: "Votre chemin vers la compagnie", title: "Votre parcours d'adoption", description: "Nous avons conçu un processus fluide et attentionné pour garantir que vous et votre nouveau compagnon soyez parfaitement assortis.", step1Title: "Découvrir et réserver", step1Desc: "Explorez nos chatons élevés avec soin, chacun avec une personnalité unique. Cliquez sur 'Réservez-moi' une fois que vous avez trouvé le match parfait.", step2Title: "Examen et approbation", step2Desc: "Après la réservation, complétez un court questionnaire sur votre mode de vie. Nos spécialistes de l'adoption et éleveurs l'examinent pour assurer le meilleur match.", step3Title: "Planifiez l'arrivée de votre chaton", step3Desc: "Nous coordonnons le retrait ou la livraison en toute sécurité et fournissons des conseils de préparation pour votre nouveau membre de la famille.", step4Title: "Certificat vétérinaire", step4Desc: "Chaque chaton doit avoir au moins 16 semaines, être correctement vacciné, négatif au FIV/FELV, examiné par un vétérinaire et disposer d'un certificat de santé valide.", step5Title: "Bienvenue à la maison", step5Desc: "Recevez votre chaton, les dossiers médicaux et célébrez ce moment spécial avec nous. Votre voyage ensemble commence !",
  },
  customerLove: {
    label: "Histoires de réussite", title: "Amour des clients 💕", description: "Écoutez les familles qui ont trouvé leurs compagnons parfaits grâce à Pawsfam.", catParent: "Parent de chat", dogParent: "Parent de chien", seeAllReviews: "Voir tous les avis →",
  },
  newsletter: {
    subscribed: "Vous êtes abonné !", subscribedDesc: "Merci de vous être abonné. Vous recevrez des mises à jour sur les nouveaux animaux, événements et conseils d'adoption.", stayUpdated: "Restez informé", description: "Abonnez-vous à notre newsletter pour des mises à jour sur les nouveaux animaux, événements d'adoption et conseils utiles pour les propriétaires d'animaux.", placeholder: "Entrez votre e-mail", subscribe: "S'abonner", subscribing: "Abonnement en cours...", privacy: "Nous respectons votre vie privée. Désabonnez-vous à tout moment.", invalidEmail: "E-mail invalide", alreadySubscribed: "Déjà abonné", alreadySubscribedDesc: "Cet e-mail est déjà abonné à notre newsletter.", success: "Abonné !", successDesc: "Vous avez été ajouté à notre newsletter.", failed: "Échec de l'abonnement", failedDesc: "Quelque chose s'est mal passé. Veuillez réessayer.",
  },
  cta: {
    title: "Prêt à trouver votre nouveau meilleur ami ?", description: "Des milliers d'animaux attendent des foyers aimants. Commencez votre parcours d'adoption aujourd'hui.", browsePets: "Parcourir les animaux disponibles", learnAbout: "En savoir plus sur l'adoption",
  },
  footer: {
    brandDesc: "Trouver des foyers aimants pour les animaux depuis 2020. Chaque animal mérite une seconde chance de bonheur.", quickLinks: "Liens rapides", availablePets: "Animaux disponibles", adoptionProcess: "Processus d'adoption", successStories: "Histoires de réussite", volunteer: "Bénévolat", catBreeds: "Races de chats", dogBreeds: "Races de chiens", support: "Support", supportLink: "Support", donateLink: "Faire un don", partnerWithUs: "Partenariat", healthGuarantee: "Garantie santé", deliveryOptions: "Options de livraison", emotionalSupport: "Soutien émotionnel", privacyPolicy: "Politique de confidentialité", termsConditions: "Conditions générales", contactUs: "Contactez-nous", copyright: "© 2026 Pawsfam. Tous droits réservés. Fait avec", forPets: "pour les animaux partout.",
  },

  // Inner Pages
  pets: { pageTitle: "Animaux disponibles à l'adoption | Pawsfam", pageDesc: "Parcourez nos chiens, chats et autres animaux disponibles à l'adoption. Trouvez votre compagnon idéal.", title: "Trouvez votre nouveau", titleHighlight: "Meilleur Ami", subtitle: "Parcourez nos animaux disponibles et trouvez votre match parfait. Chaque animal mérite un foyer aimant.", searchPlaceholder: "Rechercher par nom, race ou lieu...", filters: "Filtres", petType: "Type d'animal", size: "Taille", country: "Pays", sortBy: "Trier par", all: "Tous", allCountries: "Tous les pays", dog: "Chien", cat: "Chat", bird: "Oiseau", other: "Autre", small: "Petit", medium: "Moyen", large: "Grand", newest: "Plus récent", oldest: "Plus ancien", nameAZ: "Nom A-Z", nameZA: "Nom Z-A", petsFound: "{{count}} animaux trouvés", clearFilters: "Effacer les filtres", loadingPets: "Chargement des animaux…", noPetsFound: "Aucun animal ne correspond à vos critères" },
  petDetails: { loadingPet: "Chargement de l'animal…", petNotFound: "Animal non trouvé", petNotFoundDesc: "Désolé, nous n'avons pas trouvé l'animal que vous cherchez.", browseAvailable: "Parcourir les animaux disponibles", watch: "Regarder {{name}}", healthCerts: "Santé et certifications", about: "À propos de {{name}}", pricingSummary: "Résumé des prix", fullPayment: "Paiement intégral", deposit30: "Acompte 30%", adoptionFee: "Frais d'adoption", shipping: "Livraison", addOns: "Suppléments", reservationDeposit: "Acompte de réservation (30%)", remainingBalance: "Solde restant", total: "Total", totalDue: "Total dû", addToCart: "Ajouter au panier", reserveNow: "Réserver (Acompte 30%)", addedToCart: "Ajouté au panier !", addedToCartDesc: "{{name}} a été ajouté à votre panier.", linkCopied: "Lien copié !", linkCopiedDesc: "Partagez cet animal avec vos amis et votre famille.", geneticHealth: "Garantie santé génétique de {{years}} an(s)", fivFelv: "FIV/FeLV Négatif", fvrcp: "Vaccins FVRCP", rabies: "Vaccin antirabique", healthCert: "Certificat de santé vétérinaire", petPassport: "Passeport animal", deworming: "Vermifuge complet", microchipped: "Puce électronique", lbs: "lbs" },
  checkout: { pageTitle: "Paiement - Pawsfam", emptyCart: "Votre panier est vide", emptyCartDesc: "Ajoutez des animaux adorables pour commencer !", browsePets: "Parcourir les animaux", stepDetails: "Détails", stepPayment: "Paiement", stepConfirmation: "Confirmation", orderItems: "Articles de la commande", reservationDeposit: "Acompte de réservation 30%", fullAdoption: "Adoption complète", contactInfo: "Informations de contact", name: "Nom complet", email: "Adresse e-mail", phone: "Numéro de téléphone", address: "Adresse de livraison", message: "Notes supplémentaires", namePlaceholder: "Jean Dupont", emailPlaceholder: "vous@exemple.com", phonePlaceholder: "+33 6 12 34 56 78", addressPlaceholder: "Entrez votre adresse complète", messagePlaceholder: "Demandes spéciales ou notes...", paymentMethod: "Méthode de paiement", selectPayment: "Sélectionnez une méthode de paiement", bankTransfer: "Virement bancaire", cryptoUsdt: "USDT (TRC20)", acceptTerms: "J'accepte les", termsAndConditions: "Conditions générales", continueToPayment: "Continuer vers le paiement", backToDetails: "Retour aux détails", orderSummary: "Résumé de la commande", subtotal: "Sous-total", total: "Total", confirmPayment: "Confirmer le paiement", submitting: "Envoi en cours...", orderSuccess: "Commande envoyée avec succès !", orderSuccessDesc: "Veuillez effectuer votre paiement et télécharger le justificatif.", orderFailed: "Échec de l'envoi. Veuillez réessayer.", confirmationTitle: "Commande confirmée !", confirmationDesc: "Votre commande a été envoyée. Effectuez votre paiement avec les détails fournis.", uploadProof: "Télécharger le justificatif de paiement", returnHome: "Retour à l'accueil", secureCheckout: "Paiement sécurisé", copySuccess: "{{label}} copié !" },
  auth: { welcomeBack: "Bon retour", joinPawsfam: "Rejoignez Pawsfam", signInDesc: "Connectez-vous pour continuer votre parcours d'adoption", signUpDesc: "Créez un compte pour commencer à adopter", continueGoogle: "Continuer avec Google", connecting: "Connexion en cours...", orContinueEmail: "Ou continuer par e-mail", fullName: "Nom complet", email: "E-mail", password: "Mot de passe", signIn: "Se connecter", createAccount: "Créer un compte", pleaseWait: "Veuillez patienter...", noAccount: "Pas encore de compte ?", haveAccount: "Vous avez déjà un compte ?", signUp: "S'inscrire", signInLink: "Se connecter", loginFailed: "Échec de la connexion", invalidCredentials: "E-mail ou mot de passe incorrect.", signUpFailed: "Échec de l'inscription", alreadyRegistered: "Cet e-mail est déjà enregistré. Veuillez vous connecter.", accountCreated: "Compte créé !", accountCreatedDesc: "Vous pouvez maintenant vous connecter.", googleFailed: "Échec de la connexion Google", error: "Erreur", unexpectedError: "Une erreur inattendue s'est produite. Veuillez réessayer.", googleInitFailed: "Échec de l'initiation de la connexion Google." },
  account: { pageTitle: "Paramètres du compte", profile: "Profil", password: "Mot de passe", emails: "E-mails", adoptions: "Adoptions", foster: "Famille d'accueil", payments: "Paiements", profileInfo: "Informations du profil", updatePersonalInfo: "Mettez à jour vos informations personnelles", emailLabel: "E-mail", emailCantChange: "L'e-mail ne peut pas être modifié", fullName: "Nom complet", phoneNumber: "Numéro de téléphone", saveChanges: "Enregistrer les modifications", saving: "Enregistrement...", profileUpdated: "Profil mis à jour !", profileUpdateFailed: "Échec de la mise à jour du profil", dangerZone: "Zone dangereuse", dangerZoneDesc: "Supprimer définitivement votre compte et toutes les données associées", changePassword: "Changer le mot de passe", updatePassword: "Mettre à jour le mot de passe de votre compte", currentPassword: "Mot de passe actuel", newPassword: "Nouveau mot de passe", confirmPassword: "Confirmer le nouveau mot de passe", updatePasswordBtn: "Mettre à jour le mot de passe", updating: "Mise à jour...", passwordUpdated: "Mot de passe mis à jour !", passwordUpdateFailed: "Échec de la mise à jour du mot de passe", adoptionHistory: "Historique des adoptions", adoptionHistoryDesc: "Consultez vos demandes d'adoption et leur statut", noAdoptions: "Vous n'avez pas encore soumis de demandes d'adoption.", paymentHistory: "Historique des paiements", paymentHistoryDesc: "Consultez vos paiements et leur statut", noPayments: "Aucun enregistrement de paiement trouvé.", pending: "En attente", approved: "Approuvé", confirmed: "Confirmé", rejected: "Rejeté" },
  contact: { pageTitle: "Contactez-nous | Pawsfam", label: "Contactez-nous", title: "Nous serions ravis de", titleHighlight: "Vous entendre", subtitle: "Des questions sur l'adoption ? Vous voulez faire du bénévolat ou devenir partenaire ? Écrivez-nous !", emailLabel: "E-mail", phoneLabel: "Téléphone", phoneHours: "Lun-Ven 9h-18h", visitUs: "Rendez-nous visite", connectWithUs: "Connectez-vous avec nous", followSocial: "Suivez-nous sur les réseaux sociaux", findOnMap: "Trouvez-nous sur la carte", openGoogleMaps: "Ouvrir dans Google Maps", yourName: "Votre nom", emailAddress: "Adresse e-mail", subject: "Sujet", subjectPlaceholder: "Comment pouvons-nous vous aider ?", messageLabel: "Message", messagePlaceholder: "Dites-nous en plus sur votre demande...", sendMessage: "Envoyer le message", sending: "Envoi en cours...", messageSent: "Message envoyé !", messageSentDesc: "Nous vous répondrons dès que possible." },
  about: { pageTitle: "À propos | Pawsfam - Réseau mondial de placement d'animaux", label: "Notre réseau mondial", title: "Placement international d'animaux &", titleHighlight: "Réseau logistique", description: "Nous sommes un réseau international de placement d'animaux et de logistique travaillant avec plus de 3 000 centres d'adoption, éleveurs et établissements de soins vérifiés dans le monde entier.", statPartners: "Partenaires vérifiés dans le monde", statCountries: "Pays couverts", statFamilies: "Familles heureuses", statSupport: "Support logistique", howItWorksLabel: "Comment ça marche", howItWorksTitle: "Processus fluide de la sélection à la livraison", step1: "Les acheteurs sélectionnent un animal disponible dans un pays spécifique.", step2: "Si local — collecte directe ou transport domestique arrangé.", step3: "Si international — l'expédition est calculée selon la localisation de l'acheteur.", step4: "Le système calcule automatiquement le coût et le délai de livraison.", step5: "Une équipe de support dédiée assiste tout au long du processus.", commitmentLabel: "Notre engagement", commitmentTitle: "Ce que nous offrons", commitmentDesc: "Notre équipe d'opérations internationales travaille dans plusieurs régions pour assurer un placement sûr, la conformité et une livraison fluide.", transparentPricing: "Prix transparents", transparentPricingDesc: "Calcul d'expédition en temps réel sans frais cachés.", verifiedDocs: "Documentation vérifiée", verifiedDocsDesc: "Certificats vétérinaires complets et conformité aux réglementations internationales de transport d'animaux.", ongoingSupport: "Support continu", ongoingSupportDesc: "Équipe de support dédiée de la réservation à l'après-livraison.", securePayments: "Paiements sécurisés", securePaymentsDesc: "Plusieurs options de paiement sécurisées avec transparence totale." },
  foster: { pageTitle: "Devenir famille d'accueil | Pawsfam", title: "Devenez famille d'accueil", subtitle: "L'accueil offre un foyer temporaire aimant aux animaux jusqu'à ce qu'ils trouvent leur famille pour toujours.", saveLives: "Sauvez des vies", saveLivesDesc: "Aidez les animaux à passer des refuges à des foyers aimants", fullSupport: "Support complet", fullSupportDesc: "Nous fournissons nourriture, fournitures et soins vétérinaires", flexibleTerms: "Conditions flexibles", flexibleTermsDesc: "Choisissez un accueil à court ou long terme", applicationTitle: "Demande d'accueil", applicationDesc: "Parlez-nous de vous et de votre environnement domestique", personalInfo: "Informations personnelles", fullName: "Nom complet", email: "E-mail", phone: "Téléphone", address: "Adresse", addressPlaceholder: "Adresse complète", livingSituation: "Situation de logement", housingType: "Type de logement", selectHousing: "Sélectionnez le type de logement", house: "Maison", apartment: "Appartement", condo: "Copropriété", otherHousing: "Autre", fencedYard: "J'ai un jardin clôturé", otherPets: "J'ai d'autres animaux", otherPetsPlaceholder: "Décrivez vos autres animaux (type, âge, tempérament)", hasChildren: "J'ai des enfants à la maison", childrenAges: "Âges des enfants", experiencePrefs: "Expérience et préférences", petExperience: "Expérience avec les animaux", experiencePlaceholder: "Parlez-nous de votre expérience avec les animaux...", availability: "Disponibilité", shortTerm: "Court terme (1-4 semaines)", longTerm: "Long terme (1+ mois)", either: "L'un ou l'autre", preferredTypes: "Types d'animaux préférés", smallAnimal: "Petit animal", submitApplication: "Soumettre la demande", submitting: "Envoi en cours...", submitted: "Demande soumise !", submittedDesc: "Merci pour votre intérêt pour l'accueil ! Notre équipe examinera votre demande et vous contactera dans 3 à 5 jours ouvrables.", returnHome: "Retour à l'accueil", submitSuccess: "Demande soumise !", submitSuccessDesc: "Nous examinerons votre demande et vous contacterons bientôt.", submitFailed: "Échec de l'envoi", submitFailedDesc: "Veuillez réessayer." },
  donate: { pageTitle: "Faire un don - Soutenez nos animaux | Pawsfam", title: "Faire un don", subtitle: "Votre générosité nous aide à sauver, réhabiliter et reloger les animaux dans le besoin. Chaque contribution fait la différence.", bankTransferTitle: "Détails du virement bancaire", bankTransferDesc: "Sélectionnez votre région et transférez votre don", selectRegion: "Sélectionnez votre région", transferTo: "Transférer à ({{currency}}) :", donationDetailsTitle: "Détails du don", donationDetailsDesc: "Remplissez vos informations et téléchargez le justificatif de paiement", fullName: "Nom complet", namePlaceholder: "Votre nom", email: "E-mail", emailPlaceholder: "votre@email.com", phone: "Téléphone (facultatif)", phonePlaceholder: "Votre numéro de téléphone", amount: "Montant (USD)", amountPlaceholder: "50.00", donationType: "Type de don", oneTime: "Ponctuel", monthly: "Mensuel", messageLabel: "Message (facultatif)", messagePlaceholder: "Laissez un message avec votre don...", proofOfPayment: "Justificatif de paiement", clickToUpload: "Cliquez pour télécharger (max 5 Mo)", submitDonation: "Soumettre le don", submitting: "Envoi en cours...", thankYou: "Merci !", thankYouDesc: "Votre don a été soumis. Nous vérifierons votre paiement et vous enverrons un e-mail de confirmation.", returnHome: "Retour à l'accueil", donationSuccess: "Merci !", donationSuccessDesc: "Votre don a été soumis pour vérification.", donationFailed: "Échec de l'envoi", donationFailedDesc: "Veuillez réessayer.", proofRequired: "Justificatif requis", proofRequiredDesc: "Veuillez télécharger un justificatif de paiement.", fileTooLarge: "Fichier trop volumineux", fileTooLargeDesc: "Veuillez télécharger un fichier de moins de 5 Mo.", copied: "Copié !", copiedDesc: "{{label}} copié dans le presse-papiers." },
  reviews: { pageTitle: "Avis clients - Pawsfam", label: "Témoignages", title: "Avis clients", subtitle: "Histoires réelles de familles qui ont trouvé leurs compagnons parfaits grâce à Pawsfam. Chaque avis provient d'une adoption vérifiée.", allReviews: "Tous les avis", dogParents: "Parents de chiens", catParents: "Parents de chats", noReviews: "Aucun avis trouvé.", parent: "Parent" },

  common: {
    loading: "Chargement...", error: "Erreur", save: "Enregistrer", cancel: "Annuler", delete: "Supprimer", edit: "Modifier", back: "Retour", next: "Suivant", submit: "Soumettre", confirm: "Confirmer", close: "Fermer", search: "Rechercher", filter: "Filtrer", sortBy: "Trier par", noResults: "Aucun résultat trouvé", viewDetails: "Voir les détails", learnMore: "En savoir plus",
  },
};

export default fr;
