const id = {
  nav: { home: "Beranda", adopt: "Adopsi", reviews: "Ulasan", foster: "Asuh", donate: "Donasi", about: "Tentang", breeds: "Ras", catBreeds: "Ras Kucing", dogBreeds: "Ras Anjing", more: "Lainnya", deliveryOptions: "Opsi Pengiriman", healthGuarantee: "Jaminan Kesehatan", emotionalSupport: "Dukungan Emosional", contact: "Kontak", startAdopting: "Mulai Adopsi", admin: "Admin", orders: "Pesanan", signOut: "Keluar", signIn: "Masuk", accountSettings: "Pengaturan Akun", orderHistory: "Riwayat Pesanan", adminDashboard: "Dashboard Admin", currency: "Mata Uang", cart: "Keranjang", browsePets: "Lihat Hewan", shoppingCart: "Keranjang Belanja", item: "item", items: "item", yourCartEmpty: "Keranjang Anda kosong", deposit30: "Deposit 30%", fullAdoption: "Adopsi Penuh", moreItems: "+{{count}} item lagi", subtotal: "Subtotal", proceedToCheckout: "Lanjut ke Pembayaran" },
  hero: { badge: "Lebih dari 5.000 adopsi berhasil", title1: "Temukan", titleHighlight: "Teman", title2: "Sempurna Anda", description: "Setiap hewan peliharaan layak mendapatkan rumah yang penuh kasih. Jelajahi ratusan hewan peliharaan yang menunggu keluarga mereka dan buat perbedaan hari ini.", browsePets: "Lihat Hewan", learnMore: "Pelajari Lebih Lanjut", petsAdopted: "Hewan Diadopsi", verifiedShelters: "Shelter Terverifikasi", support247: "Dukungan", slideAlt: "Slideshow hewan {{index}}", goToSlide: "Ke slide {{index}}" },
  howItWorks: { label: "Proses Sederhana", title: "Cara Adopsi Bekerja", description: "Kami membuat proses adopsi sederhana dan bebas stres. Begini cara membawa pulang sahabat baru Anda.", step1Title: "Lihat Hewan", step1Desc: "Jelajahi galeri hewan peliharaan lucu yang mencari rumah selamanya.", step2Title: "Daftar Online", step2Desc: "Isi formulir adopsi sederhana kami dengan data Anda.", step3Title: "Pertemuan", step3Desc: "Jadwalkan kunjungan untuk bertemu calon anggota keluarga baru Anda.", step4Title: "Selamat Datang di Rumah", step4Desc: "Selesaikan adopsi dan bawa pulang teman baru Anda!" },
  featured: { label: "Teman Unggulan", title: "Hewan Menunggu Anda", description: "Kenali beberapa hewan peliharaan lucu kami yang siap menjadi bagian keluarga Anda.", viewAllPets: "Lihat Semua Hewan", justAdded: "Baru Ditambahkan", newArrivals: "Pendatang Baru", newArrivalsDesc: "Lihat hewan terbaru yang mencari rumah selamanya.", seeAllNewPets: "Lihat Semua Hewan Baru", dogsLabel: "🐕 Anjing", dogsTitle: "Anjing Tersedia untuk Adopsi", dogsDesc: "Temukan teman anjing sempurna dari koleksi anjing lucu kami.", viewAllDogs: "Lihat Semua Anjing", catsLabel: "🐈 Kucing", catsTitle: "Kucing Tersedia untuk Adopsi", catsDesc: "Temukan kucing manis dan playful yang menunggu rumah penuh kasih.", viewAllCats: "Lihat Semua Kucing" },
  trust: { title: "Kami Mengutamakan Pembibitan Etis dan Kesejahteraan Hewan", description: "Komitmen kami terhadap keunggulan didukung oleh organisasi terkemuka yang menetapkan standar tertinggi untuk perawatan hewan dan praktik pembibitan.", cfaFull: "Asosiasi Pecinta Kucing", cfaDesc: "Registri kucing ras terbesar di dunia, menetapkan standar ras kucing sejak 1906.", ticaFull: "Asosiasi Kucing Internasional", ticaDesc: "Registri genetik terbesar di dunia untuk kucing ras dan rumahan, mempromosikan kepemilikan kucing yang bertanggung jawab.", usdaFull: "Departemen Pertanian AS", usdaDesc: "Lembaga regulasi federal yang memastikan standar kesejahteraan hewan dan sertifikasi kesehatan untuk transportasi hewan.", certifiedNote: "Semua peternak kami bersertifikat dan diperiksa secara rutin untuk memastikan standar perawatan tertinggi." },
  journey: { label: "Jalan Anda Menuju Persahabatan", title: "Perjalanan Adopsi Anda", description: "Kami merancang proses yang mulus dan penuh perhatian untuk memastikan Anda dan teman baru Anda cocok sempurna.", step1Title: "Temukan dan Pesan", step1Desc: "Jelajahi anak kucing kami yang dirawat dengan penuh kasih, masing-masing dengan kepribadian unik. Klik 'Pesan' saat Anda menemukan pasangan sempurna.", step2Title: "Tinjauan dan Persetujuan", step2Desc: "Setelah pemesanan, isi kuesioner gaya hidup singkat. Spesialis kami meninjau untuk memastikan kecocokan terbaik.", step3Title: "Rencanakan Kedatangan Anak Kucing", step3Desc: "Kami mengkoordinasikan pengambilan atau pengiriman yang aman dan memberikan panduan persiapan.", step4Title: "Sertifikasi Dokter Hewan", step4Desc: "Setiap anak kucing harus berusia minimal 16 minggu, divaksinasi dengan benar, FIV/FELV negatif, diperiksa dokter hewan, dan memiliki sertifikat kesehatan yang valid.", step5Title: "Selamat Datang di Rumah", step5Desc: "Terima anak kucing Anda, catatan medis, dan rayakan momen spesial ini bersama kami. Perjalanan bersama Anda dimulai!" },
  customerLove: { label: "Kisah Sukses", title: "Cinta Pelanggan 💕", description: "Dengarkan dari keluarga yang menemukan teman sempurna mereka melalui Pawsfam.", catParent: "Orang Tua Kucing", dogParent: "Orang Tua Anjing", seeAllReviews: "Lihat Semua Ulasan →" },
  newsletter: { subscribed: "Anda Berlangganan!", subscribedDesc: "Terima kasih telah berlangganan. Anda akan menerima update tentang hewan baru, acara, dan tips adopsi.", stayUpdated: "Tetap Update", description: "Berlangganan newsletter kami untuk update tentang hewan baru, acara adopsi, dan tips berguna.", placeholder: "Masukkan email Anda", subscribe: "Berlangganan", subscribing: "Berlangganan...", privacy: "Kami menghormati privasi Anda. Berhenti berlangganan kapan saja.", invalidEmail: "Email tidak valid", alreadySubscribed: "Sudah berlangganan", alreadySubscribedDesc: "Email ini sudah berlangganan newsletter kami.", success: "Berlangganan!", successDesc: "Anda telah ditambahkan ke newsletter kami.", failed: "Berlangganan gagal", failedDesc: "Terjadi kesalahan. Silakan coba lagi." },
  cta: { title: "Siap Menemukan Sahabat Baru Anda?", description: "Ribuan hewan peliharaan menunggu rumah penuh kasih. Mulai perjalanan adopsi Anda hari ini.", browsePets: "Lihat Hewan Tersedia", learnAbout: "Pelajari Tentang Adopsi" },
  footer: { brandDesc: "Menemukan rumah penuh kasih untuk hewan peliharaan sejak 2020. Setiap hewan layak mendapatkan kesempatan kedua untuk bahagia.", quickLinks: "Tautan Cepat", availablePets: "Hewan Tersedia", adoptionProcess: "Proses Adopsi", successStories: "Kisah Sukses", volunteer: "Relawan", catBreeds: "Ras Kucing", dogBreeds: "Ras Anjing", support: "Dukungan", supportLink: "Dukungan", donateLink: "Donasi", partnerWithUs: "Bermitra dengan Kami", healthGuarantee: "Jaminan Kesehatan", deliveryOptions: "Opsi Pengiriman", emotionalSupport: "Dukungan Emosional", privacyPolicy: "Kebijakan Privasi", termsConditions: "Syarat & Ketentuan", contactUs: "Hubungi Kami", copyright: "© 2026 Pawsfam. Hak cipta dilindungi. Dibuat dengan", forPets: "untuk hewan peliharaan di mana saja." },
  common: { loading: "Memuat...", error: "Kesalahan", save: "Simpan", cancel: "Batal", delete: "Hapus", edit: "Edit", back: "Kembali", next: "Selanjutnya", submit: "Kirim", confirm: "Konfirmasi", close: "Tutup", search: "Cari", filter: "Filter", sortBy: "Urutkan", noResults: "Tidak ada hasil", viewDetails: "Lihat Detail", learnMore: "Pelajari Lebih Lanjut" },
};

export default id;
