const ja = {
  nav: { home: "ホーム", adopt: "里親になる", reviews: "レビュー", foster: "一時預かり", donate: "寄付", about: "私たちについて", breeds: "品種", catBreeds: "猫の品種", dogBreeds: "犬の品種", more: "もっと", deliveryOptions: "配送オプション", healthGuarantee: "健康保証", emotionalSupport: "心のサポート", contact: "お問い合わせ", startAdopting: "里親を始める", admin: "管理", orders: "注文", signOut: "ログアウト", signIn: "ログイン", accountSettings: "アカウント設定", orderHistory: "注文履歴", adminDashboard: "管理ダッシュボード", currency: "通貨", cart: "カート", browsePets: "ペットを見る", shoppingCart: "ショッピングカート", item: "点", items: "点", yourCartEmpty: "カートは空です", deposit30: "30%前金", fullAdoption: "全額里親", moreItems: "+{{count}}点", subtotal: "小計", proceedToCheckout: "レジに進む" },
  hero: { badge: "5,000件以上の里親実績", title1: "あなたの", titleHighlight: "理想の", title2: "パートナーを見つけよう", description: "すべてのペットは愛のある家庭に値します。永遠の家族を待つ何百ものかわいいペットを見て、今日違いを作りましょう。", browsePets: "ペットを見る", learnMore: "詳しく知る", petsAdopted: "里親実績", verifiedShelters: "認定シェルター", support247: "サポート", slideAlt: "ペットスライドショー {{index}}", goToSlide: "スライド {{index}} へ" },
  howItWorks: { label: "簡単なプロセス", title: "里親の仕組み", description: "里親のプロセスをシンプルでストレスフリーにしました。新しい親友を家に迎える方法はこちらです。", step1Title: "ペットを見る", step1Desc: "永遠の家を探しているかわいいペットのギャラリーをご覧ください。", step2Title: "オンラインで申し込む", step2Desc: "簡単な里親申請書にご記入ください。", step3Title: "お見合い", step3Desc: "新しい家族候補に会う訪問を予約しましょう。", step4Title: "ようこそ我が家へ", step4Desc: "里親手続きを完了し、新しいパートナーを家に迎えましょう！" },
  featured: { label: "注目の仲間たち", title: "あなたを待つペットたち", description: "あなたの家族になる準備ができているかわいいペットたちに会いましょう。", viewAllPets: "すべてのペットを見る", justAdded: "新着", newArrivals: "新しい仲間", newArrivalsDesc: "永遠の家を探している最新のペットをチェックしてください。", seeAllNewPets: "すべての新しいペットを見る", dogsLabel: "🐕 犬", dogsTitle: "里親募集中の犬", dogsDesc: "愛らしい犬の中からあなたにぴったりの犬のパートナーを見つけましょう。", viewAllDogs: "すべての犬を見る", catsLabel: "🐈 猫", catsTitle: "里親募集中の猫", catsDesc: "愛のある家を待つ甘くて遊び好きな猫たちを見つけましょう。", viewAllCats: "すべての猫を見る" },
  trust: { title: "倫理的な繁殖と動物福祉を優先します", description: "私たちの卓越性への取り組みは、動物のケアと繁殖慣行の最高基準を設定する業界をリードする組織によって支えられています。", cfaFull: "猫愛好家協会", cfaDesc: "1906年以来、猫の品種の基準を設定している世界最大の血統猫登録機関。", ticaFull: "国際猫協会", ticaDesc: "責任ある猫の飼育を推進する世界最大の血統猫・家猫の遺伝子登録機関。", usdaFull: "米国農務省", usdaDesc: "ペット輸送の動物福祉基準と健康認証を確保する連邦規制機関。", certifiedNote: "すべてのブリーダーは認定されており、最高のケア基準を確保するために定期的に検査されています。" },
  journey: { label: "コンパニオンへの道", title: "あなたの里親の旅", description: "あなたと新しいパートナーが完璧にマッチするように、シームレスで思いやりのあるプロセスを設計しました。", step1Title: "発見して予約", step1Desc: "それぞれユニークな性格を持つ子猫をご覧ください。完璧なマッチを見つけたら「予約」をクリック。", step2Title: "審査と承認", step2Desc: "予約後、簡単なライフスタイルアンケートにご記入ください。専門家が最適なマッチングを確認します。", step3Title: "子猫の到着を計画", step3Desc: "安全な引き取りまたは配達を調整し、新しい家族の準備ガイダンスを提供します。", step4Title: "獣医検査", step4Desc: "各子猫は16週齢以上で、適切にワクチン接種済み、FIV/FELV陰性、獣医検査済み、有効な健康証明書が必要です。", step5Title: "ようこそ我が家へ", step5Desc: "子猫、医療記録を受け取り、この特別な瞬間をお祝いしましょう。一緒の旅が始まります！" },
  customerLove: { label: "成功事例", title: "お客様の愛 💕", description: "Pawsfamを通じて完璧なパートナーを見つけた家族の声をお聞きください。", catParent: "猫の親", dogParent: "犬の親", seeAllReviews: "すべてのレビューを見る →" },
  newsletter: { subscribed: "購読完了！", subscribedDesc: "ご購読ありがとうございます。新しいペット、イベント、里親のヒントに関する更新情報をお届けします。", stayUpdated: "最新情報を入手", description: "新しいペット、里親イベント、ペットオーナー向けの便利なヒントの更新情報を受け取るにはニュースレターを購読してください。", placeholder: "メールアドレスを入力", subscribe: "購読する", subscribing: "購読中...", privacy: "プライバシーを尊重します。いつでも解除できます。", invalidEmail: "無効なメールアドレス", alreadySubscribed: "購読済み", alreadySubscribedDesc: "このメールアドレスは既に購読されています。", success: "購読完了！", successDesc: "ニュースレターに追加されました。", failed: "購読に失敗", failedDesc: "問題が発生しました。もう一度お試しください。" },
  cta: { title: "新しい親友を見つける準備はできましたか？", description: "何千ものペットが愛のある家を待っています。今日から里親の旅を始めましょう。", browsePets: "利用可能なペットを見る", learnAbout: "里親について知る" },
  footer: { brandDesc: "2020年からペットに愛のある家を見つけています。すべてのペットは幸せの第二のチャンスに値します。", quickLinks: "クイックリンク", availablePets: "利用可能なペット", adoptionProcess: "里親プロセス", successStories: "成功事例", volunteer: "ボランティア", catBreeds: "猫の品種", dogBreeds: "犬の品種", support: "サポート", supportLink: "サポート", donateLink: "寄付", partnerWithUs: "パートナーになる", healthGuarantee: "健康保証", deliveryOptions: "配送オプション", emotionalSupport: "心のサポート", privacyPolicy: "プライバシーポリシー", termsConditions: "利用規約", contactUs: "お問い合わせ", copyright: "© 2026 Pawsfam。無断転載を禁じます。", forPets: "世界中のペットのために作られました。" },
  common: { loading: "読み込み中...", error: "エラー", save: "保存", cancel: "キャンセル", delete: "削除", edit: "編集", back: "戻る", next: "次へ", submit: "送信", confirm: "確認", close: "閉じる", search: "検索", filter: "フィルター", sortBy: "並び替え", noResults: "結果が見つかりません", viewDetails: "詳細を見る", learnMore: "詳しく知る" },
};

export default ja;
