const ko = {
  nav: { home: "홈", adopt: "입양", reviews: "후기", foster: "임시보호", donate: "기부", about: "소개", breeds: "품종", catBreeds: "고양이 품종", dogBreeds: "강아지 품종", more: "더보기", deliveryOptions: "배송 옵션", healthGuarantee: "건강 보증", emotionalSupport: "정서적 지원", contact: "연락처", startAdopting: "입양 시작", admin: "관리", orders: "주문", signOut: "로그아웃", signIn: "로그인", accountSettings: "계정 설정", orderHistory: "주문 내역", adminDashboard: "관리 대시보드", currency: "통화", cart: "장바구니", browsePets: "반려동물 보기", shoppingCart: "장바구니", item: "개", items: "개", yourCartEmpty: "장바구니가 비어 있습니다", deposit30: "30% 보증금", fullAdoption: "전액 입양", moreItems: "+{{count}}개 더", subtotal: "소계", proceedToCheckout: "결제하기" },
  hero: { badge: "5,000건 이상의 성공적인 입양", title1: "당신의", titleHighlight: "완벽한", title2: "반려동물을 찾으세요", description: "모든 반려동물은 사랑하는 가정을 받을 자격이 있습니다. 영원한 가족을 기다리는 수백 마리의 사랑스러운 반려동물을 둘러보고 오늘 변화를 만드세요.", browsePets: "반려동물 보기", learnMore: "자세히 알아보기", petsAdopted: "입양된 반려동물", verifiedShelters: "인증된 보호소", support247: "지원", slideAlt: "반려동물 슬라이드쇼 {{index}}", goToSlide: "슬라이드 {{index}}로 이동" },
  howItWorks: { label: "간단한 과정", title: "입양 방법", description: "입양 과정을 간단하고 스트레스 없이 만들었습니다. 새로운 가장 친한 친구를 집에 데려오는 방법입니다.", step1Title: "반려동물 보기", step1Desc: "영원한 집을 찾는 사랑스러운 반려동물 갤러리를 탐색하세요.", step2Title: "온라인 신청", step2Desc: "간단한 입양 신청서를 작성하세요.", step3Title: "만남", step3Desc: "새로운 가족 후보를 만나는 방문을 예약하세요.", step4Title: "집으로 환영", step4Desc: "입양을 완료하고 새로운 반려동물을 집에 데려오세요!" },
  featured: { label: "추천 친구들", title: "당신을 기다리는 반려동물", description: "가족이 될 준비가 된 사랑스러운 반려동물들을 만나보세요.", viewAllPets: "모든 반려동물 보기", justAdded: "새로 추가됨", newArrivals: "신규 입소", newArrivalsDesc: "영원한 집을 찾는 최신 반려동물을 확인하세요.", seeAllNewPets: "모든 새 반려동물 보기", dogsLabel: "🐕 강아지", dogsTitle: "입양 가능한 강아지", dogsDesc: "사랑스러운 강아지 중에서 완벽한 반려견을 찾으세요.", viewAllDogs: "모든 강아지 보기", catsLabel: "🐈 고양이", catsTitle: "입양 가능한 고양이", catsDesc: "사랑하는 집을 기다리는 달콤하고 장난기 많은 고양이를 만나보세요.", viewAllCats: "모든 고양이 보기" },
  trust: { title: "윤리적 번식과 동물 복지를 최우선으로 합니다", description: "우수성에 대한 우리의 약속은 동물 관리 및 번식 관행의 최고 기준을 설정하는 업계 선도 기관의 지원을 받습니다.", cfaFull: "고양이 애호가 협회", cfaDesc: "1906년부터 고양이 품종 기준을 설정해 온 세계 최대 혈통 고양이 등록 기관.", ticaFull: "국제 고양이 협회", ticaDesc: "책임 있는 고양이 소유를 촉진하는 세계 최대 혈통 및 가정 고양이 유전자 등록 기관.", usdaFull: "미국 농무부", usdaDesc: "반려동물 운송의 동물 복지 기준과 건강 인증을 보장하는 연방 규제 기관.", certifiedNote: "모든 브리더는 인증을 받았으며 최고의 관리 기준을 보장하기 위해 정기적으로 검사를 받습니다." },
  journey: { label: "반려의 길", title: "입양 여정", description: "당신과 새로운 반려동물이 완벽하게 어울리도록 매끄럽고 세심한 과정을 설계했습니다.", step1Title: "발견 및 예약", step1Desc: "각각 독특한 성격을 가진 세심하게 기른 새끼 고양이를 탐색하세요. 완벽한 매칭을 찾으면 '예약하기'를 클릭하세요.", step2Title: "검토 및 승인", step2Desc: "예약 후 간단한 생활 방식 설문지를 작성하세요. 전문가가 최적의 매칭을 검토합니다.", step3Title: "새끼 고양이 도착 계획", step3Desc: "안전한 픽업 또는 배달을 조율하고 새 가족을 위한 준비 가이드를 제공합니다.", step4Title: "수의사 검사", step4Desc: "각 새끼 고양이는 최소 16주 이상, 적절한 예방 접종, FIV/FELV 음성, 수의사 검사 및 유효한 건강 증명서가 필요합니다.", step5Title: "집으로 환영", step5Desc: "새끼 고양이, 의료 기록을 받고 이 특별한 순간을 함께 축하하세요. 함께하는 여정이 시작됩니다!" },
  customerLove: { label: "성공 사례", title: "고객의 사랑 💕", description: "Pawsfam을 통해 완벽한 반려동물을 찾은 가족들의 이야기를 들어보세요.", catParent: "고양이 부모", dogParent: "강아지 부모", seeAllReviews: "모든 후기 보기 →" },
  newsletter: { subscribed: "구독 완료!", subscribedDesc: "구독해 주셔서 감사합니다. 새로운 반려동물, 이벤트 및 입양 팁에 대한 업데이트를 받으실 수 있습니다.", stayUpdated: "최신 소식 받기", description: "새로운 반려동물, 입양 이벤트 및 유용한 팁에 대한 업데이트를 받으려면 뉴스레터를 구독하세요.", placeholder: "이메일을 입력하세요", subscribe: "구독", subscribing: "구독 중...", privacy: "개인정보를 존중합니다. 언제든지 구독을 취소할 수 있습니다.", invalidEmail: "잘못된 이메일", alreadySubscribed: "이미 구독 중", alreadySubscribedDesc: "이 이메일은 이미 뉴스레터를 구독하고 있습니다.", success: "구독 완료!", successDesc: "뉴스레터에 추가되었습니다.", failed: "구독 실패", failedDesc: "문제가 발생했습니다. 다시 시도해 주세요." },
  cta: { title: "새로운 가장 친한 친구를 찾을 준비가 되셨나요?", description: "수천 마리의 반려동물이 사랑하는 집을 기다리고 있습니다. 오늘 입양 여정을 시작하세요.", browsePets: "입양 가능한 반려동물 보기", learnAbout: "입양에 대해 알아보기" },
  footer: { brandDesc: "2020년부터 반려동물에게 사랑하는 집을 찾아주고 있습니다. 모든 반려동물은 행복의 두 번째 기회를 받을 자격이 있습니다.", quickLinks: "빠른 링크", availablePets: "입양 가능한 반려동물", adoptionProcess: "입양 과정", successStories: "성공 사례", volunteer: "봉사활동", catBreeds: "고양이 품종", dogBreeds: "강아지 품종", support: "지원", supportLink: "지원", donateLink: "기부", partnerWithUs: "파트너 되기", healthGuarantee: "건강 보증", deliveryOptions: "배송 옵션", emotionalSupport: "정서적 지원", privacyPolicy: "개인정보 보호정책", termsConditions: "이용약관", contactUs: "연락처", copyright: "© 2026 Pawsfam. 모든 권리 보유.", forPets: "전 세계 반려동물을 위해 만들었습니다." },
  common: { loading: "로딩 중...", error: "오류", save: "저장", cancel: "취소", delete: "삭제", edit: "편집", back: "뒤로", next: "다음", submit: "제출", confirm: "확인", close: "닫기", search: "검색", filter: "필터", sortBy: "정렬", noResults: "결과 없음", viewDetails: "상세 보기", learnMore: "자세히 알아보기" },
};

export default ko;
