const nl = {
  nav: { home: "Home", adopt: "Adopteer", reviews: "Beoordelingen", foster: "Pleegzorg", donate: "Doneer", about: "Over ons", breeds: "Rassen", catBreeds: "Kattenrassen", dogBreeds: "Hondenrassen", more: "Meer", deliveryOptions: "Bezorgopties", healthGuarantee: "Gezondheidsgarantie", emotionalSupport: "Emotionele steun", contact: "Contact", startAdopting: "Begin met adopteren", admin: "Admin", orders: "Bestellingen", signOut: "Uitloggen", signIn: "Inloggen", accountSettings: "Accountinstellingen", orderHistory: "Bestelgeschiedenis", adminDashboard: "Admin dashboard", currency: "Valuta", cart: "Winkelwagen", browsePets: "Dieren bekijken", shoppingCart: "Winkelwagen", item: "item", items: "items", yourCartEmpty: "Je winkelwagen is leeg", deposit30: "30% aanbetaling", fullAdoption: "Volledige adoptie", moreItems: "+{{count}} meer item(s)", subtotal: "Subtotaal", proceedToCheckout: "Naar afrekenen" },
  hero: { badge: "Meer dan 5.000 succesvolle adopties", title1: "Vind jouw", titleHighlight: "Perfecte", title2: "Metgezel", description: "Elk dier verdient een liefdevol thuis. Bekijk honderden schattige dieren die wachten op hun families en maak vandaag het verschil.", browsePets: "Dieren bekijken", learnMore: "Meer informatie", petsAdopted: "Geadopteerde dieren", verifiedShelters: "Geverifieerde asielen", support247: "Ondersteuning", slideAlt: "Dieren diashow {{index}}", goToSlide: "Ga naar dia {{index}}" },
  howItWorks: { label: "Eenvoudig proces", title: "Hoe adoptie werkt", description: "We hebben het adoptieproces eenvoudig en stressvrij gemaakt. Zo kun je je nieuwe beste vriend mee naar huis nemen.", step1Title: "Dieren bekijken", step1Desc: "Verken onze galerij van schattige dieren op zoek naar hun thuis.", step2Title: "Online aanmelden", step2Desc: "Vul onze eenvoudige adoptieaanvraag in met je gegevens.", step3Title: "Kennismaking", step3Desc: "Plan een bezoek om je potentiële nieuwe gezinslid te ontmoeten.", step4Title: "Welkom thuis", step4Desc: "Voltooi de adoptie en breng je nieuwe metgezel mee naar huis!" },
  featured: { label: "Uitgelichte vrienden", title: "Dieren wachten op jou", description: "Maak kennis met enkele van onze schattige dieren die klaar zijn om deel uit te maken van je gezin.", viewAllPets: "Alle dieren bekijken", justAdded: "Net toegevoegd", newArrivals: "Nieuw binnen", newArrivalsDesc: "Bekijk de nieuwste dieren op zoek naar hun thuis.", seeAllNewPets: "Alle nieuwe dieren bekijken", dogsLabel: "🐕 Honden", dogsTitle: "Honden beschikbaar voor adoptie", dogsDesc: "Vind je perfecte hondenmetgezel uit onze selectie van lieve honden.", viewAllDogs: "Alle honden bekijken", catsLabel: "🐈 Katten", catsTitle: "Katten beschikbaar voor adoptie", catsDesc: "Ontdek lieve en speelse katten die wachten op een liefdevol thuis.", viewAllCats: "Alle katten bekijken" },
  trust: { title: "Wij geven prioriteit aan ethisch fokken en dierenwelzijn", description: "Onze toewijding aan excellentie wordt ondersteund door toonaangevende organisaties die de hoogste normen stellen voor dierenverzorging en fokpraktijken.", cfaFull: "Cat Fanciers' Association", cfaDesc: "Het grootste raskattenregister ter wereld, dat sinds 1906 de standaard zet voor kattenrassen.", ticaFull: "De Internationale Kattenvereniging", ticaDesc: "Het grootste genetische register ter wereld van raskatten en huiskatten, ter bevordering van verantwoord kattenbezit.", usdaFull: "US Department of Agriculture", usdaDesc: "Federaal regelgevend agentschap dat normen voor dierenwelzijn en gezondheidscertificeringen voor dierenvervoer waarborgt.", certifiedNote: "Al onze fokkers zijn gecertificeerd en worden regelmatig geïnspecteerd om de hoogste verzorgingsnormen te garanderen." },
  journey: { label: "Jouw pad naar gezelschap", title: "Jouw adoptiereis", description: "We hebben een naadloos, zorgzaam proces ontworpen om ervoor te zorgen dat jij en je nieuwe metgezel perfect bij elkaar passen.", step1Title: "Ontdek en reserveer", step1Desc: "Verken onze zorgvuldig opgegroeide kittens, elk met een unieke persoonlijkheid. Klik op 'Reserveer mij' wanneer je de perfecte match hebt gevonden.", step2Title: "Beoordeling en goedkeuring", step2Desc: "Na reservering vul je een korte levensstijl vragenlijst in. Onze specialisten beoordelen deze voor de beste match.", step3Title: "Plan de aankomst van je kitten", step3Desc: "Wij coördineren veilige ophaal of bezorging en bieden voorbereidingsrichtlijnen voor je nieuwe gezinslid.", step4Title: "Veterinaire goedkeuring", step4Desc: "Elk kitten moet minimaal 16 weken oud zijn, correct gevaccineerd, FIV/FELV negatief, door een dierenarts gecontroleerd en voorzien van een geldig gezondheidscertificaat.", step5Title: "Welkom thuis", step5Desc: "Ontvang je kitten, medische dossiers en vier dit speciale moment met ons. Jullie reis samen begint!" },
  customerLove: { label: "Succesverhalen", title: "Klantenliefde 💕", description: "Hoor van gezinnen die hun perfecte metgezellen via Pawsfam hebben gevonden.", catParent: "Kattenouder", dogParent: "Hondenouder", seeAllReviews: "Alle beoordelingen bekijken →" },
  newsletter: { subscribed: "Je bent geabonneerd!", subscribedDesc: "Bedankt voor je abonnement. Je ontvangt updates over nieuwe dieren, evenementen en adoptietips.", stayUpdated: "Blijf op de hoogte", description: "Abonneer je op onze nieuwsbrief voor updates over nieuwe dieren, adoptie-evenementen en handige tips voor dierenbezitters.", placeholder: "Voer je e-mail in", subscribe: "Abonneren", subscribing: "Bezig met abonneren...", privacy: "We respecteren je privacy. Op elk moment opzegbaar.", invalidEmail: "Ongeldig e-mailadres", alreadySubscribed: "Al geabonneerd", alreadySubscribedDesc: "Dit e-mailadres is al geabonneerd op onze nieuwsbrief.", success: "Geabonneerd!", successDesc: "Je bent toegevoegd aan onze nieuwsbrief.", failed: "Abonnement mislukt", failedDesc: "Er is iets misgegaan. Probeer het opnieuw." },
  cta: { title: "Klaar om je nieuwe beste vriend te vinden?", description: "Duizenden dieren wachten op een liefdevol thuis. Begin vandaag met je adoptiereis.", browsePets: "Beschikbare dieren bekijken", learnAbout: "Meer over adoptie" },
  footer: { brandDesc: "Sinds 2020 liefdevolle huizen vinden voor dieren. Elk dier verdient een tweede kans op geluk.", quickLinks: "Snelkoppelingen", availablePets: "Beschikbare dieren", adoptionProcess: "Adoptieproces", successStories: "Succesverhalen", volunteer: "Vrijwilligerswerk", catBreeds: "Kattenrassen", dogBreeds: "Hondenrassen", support: "Ondersteuning", supportLink: "Ondersteuning", donateLink: "Doneer", partnerWithUs: "Word partner", healthGuarantee: "Gezondheidsgarantie", deliveryOptions: "Bezorgopties", emotionalSupport: "Emotionele steun", privacyPolicy: "Privacybeleid", termsConditions: "Algemene voorwaarden", contactUs: "Neem contact op", copyright: "© 2026 Pawsfam. Alle rechten voorbehouden. Gemaakt met", forPets: "voor dieren overal." },
  common: { loading: "Laden...", error: "Fout", save: "Opslaan", cancel: "Annuleren", delete: "Verwijderen", edit: "Bewerken", back: "Terug", next: "Volgende", submit: "Verzenden", confirm: "Bevestigen", close: "Sluiten", search: "Zoeken", filter: "Filteren", sortBy: "Sorteren op", noResults: "Geen resultaten gevonden", viewDetails: "Details bekijken", learnMore: "Meer informatie" },
};

export default nl;
