const pl = {
  nav: { home: "Strona główna", adopt: "Adoptuj", reviews: "Opinie", foster: "Piecza zastępcza", donate: "Wspieraj", about: "O nas", breeds: "Rasy", catBreeds: "Rasy kotów", dogBreeds: "Rasy psów", more: "Więcej", deliveryOptions: "Opcje dostawy", healthGuarantee: "Gwarancja zdrowia", emotionalSupport: "Wsparcie emocjonalne", contact: "Kontakt", startAdopting: "Zacznij adoptować", admin: "Admin", orders: "Zamówienia", signOut: "Wyloguj", signIn: "Zaloguj", accountSettings: "Ustawienia konta", orderHistory: "Historia zamówień", adminDashboard: "Panel administracyjny", currency: "Waluta", cart: "Koszyk", browsePets: "Przeglądaj zwierzęta", shoppingCart: "Koszyk zakupowy", item: "przedmiot", items: "przedmiotów", yourCartEmpty: "Twój koszyk jest pusty", deposit30: "30% zaliczki", fullAdoption: "Pełna adopcja", moreItems: "+{{count}} więcej", subtotal: "Suma częściowa", proceedToCheckout: "Przejdź do płatności" },
  hero: { badge: "Ponad 5 000 udanych adopcji", title1: "Znajdź swojego", titleHighlight: "Idealnego", title2: "Towarzysza", description: "Każde zwierzę zasługuje na kochający dom. Przeglądaj setki uroczych zwierząt czekających na swoje rodziny i zrób różnicę już dziś.", browsePets: "Przeglądaj zwierzęta", learnMore: "Dowiedz się więcej", petsAdopted: "Adoptowane zwierzęta", verifiedShelters: "Zweryfikowane schroniska", support247: "Wsparcie", slideAlt: "Pokaz slajdów zwierząt {{index}}", goToSlide: "Przejdź do slajdu {{index}}" },
  howItWorks: { label: "Prosty proces", title: "Jak działa adopcja", description: "Uprościliśmy proces adopcji, aby był bezstresowy. Oto jak możesz zabrać do domu nowego najlepszego przyjaciela.", step1Title: "Przeglądaj zwierzęta", step1Desc: "Odkryj naszą galerię uroczych zwierząt szukających swojego domu na zawsze.", step2Title: "Złóż wniosek online", step2Desc: "Wypełnij nasz prosty formularz adopcyjny swoimi danymi.", step3Title: "Spotkanie", step3Desc: "Zaplanuj wizytę, aby poznać potencjalnego nowego członka rodziny.", step4Title: "Witaj w domu", step4Desc: "Zakończ adopcję i zabierz nowego towarzysza do domu!" },
  featured: { label: "Wyróżnieni przyjaciele", title: "Zwierzęta czekają na Ciebie", description: "Poznaj niektóre z naszych uroczych zwierząt gotowych stać się częścią Twojej rodziny.", viewAllPets: "Zobacz wszystkie zwierzęta", justAdded: "Właśnie dodane", newArrivals: "Nowo przybyłe", newArrivalsDesc: "Sprawdź najnowsze zwierzęta szukające domu na zawsze.", seeAllNewPets: "Zobacz wszystkie nowe zwierzęta", dogsLabel: "🐕 Psy", dogsTitle: "Psy do adopcji", dogsDesc: "Znajdź idealnego psiego towarzysza z naszej kolekcji kochanych psów.", viewAllDogs: "Zobacz wszystkie psy", catsLabel: "🐈 Koty", catsTitle: "Koty do adopcji", catsDesc: "Odkryj słodkie i figlarnie koty czekające na kochający dom.", viewAllCats: "Zobacz wszystkie koty" },
  trust: { title: "Priorytetowo traktujemy etyczną hodowlę i dobrostan zwierząt", description: "Nasze zaangażowanie w doskonałość jest wspierane przez wiodące organizacje branżowe, które wyznaczają najwyższe standardy opieki nad zwierzętami i praktyk hodowlanych.", cfaFull: "Stowarzyszenie Miłośników Kotów", cfaDesc: "Największy na świecie rejestr rasowych kotów, wyznaczający standardy ras kotów od 1906 roku.", ticaFull: "Międzynarodowe Stowarzyszenie Kotów", ticaDesc: "Największy na świecie rejestr genetyczny kotów rasowych i domowych, promujący odpowiedzialne posiadanie kotów.", usdaFull: "Departament Rolnictwa USA", usdaDesc: "Federalna agencja regulacyjna zapewniająca standardy dobrostanu zwierząt i certyfikaty zdrowotne dla transportu zwierząt.", certifiedNote: "Wszyscy nasi hodowcy są certyfikowani i regularnie kontrolowani, aby zapewnić najwyższe standardy opieki." },
  journey: { label: "Twoja droga do towarzystwa", title: "Twoja podróż adopcyjna", description: "Zaprojektowaliśmy płynny, troskliwy proces, aby zapewnić idealne dopasowanie Ciebie i Twojego nowego towarzysza.", step1Title: "Odkryj i zarezerwuj", step1Desc: "Poznaj nasze starannie wychowane kocięta, każde z unikalną osobowością. Kliknij 'Zarezerwuj', gdy znajdziesz idealne dopasowanie.", step2Title: "Przegląd i zatwierdzenie", step2Desc: "Po rezerwacji wypełnij krótką ankietę dotyczącą stylu życia. Nasi specjaliści ją sprawdzą.", step3Title: "Zaplanuj przybycie kociaka", step3Desc: "Koordynujemy bezpieczny odbiór lub dostawę i zapewniamy wskazówki przygotowawcze.", step4Title: "Zaświadczenie weterynaryjne", step4Desc: "Każdy kociak musi mieć co najmniej 16 tygodni, być prawidłowo zaszczepiony, mieć negatywny wynik FIV/FELV, przebadany przez weterynarza i ważne świadectwo zdrowia.", step5Title: "Witaj w domu", step5Desc: "Odbierz kociaka, dokumentację medyczną i świętuj ten wyjątkowy moment z nami. Wasza wspólna podróż się zaczyna!" },
  customerLove: { label: "Historie sukcesu", title: "Miłość klientów 💕", description: "Posłuchaj rodzin, które znalazły swoich idealnych towarzyszy przez Pawsfam.", catParent: "Rodzic kota", dogParent: "Rodzic psa", seeAllReviews: "Zobacz wszystkie opinie →" },
  newsletter: { subscribed: "Jesteś subskrybentem!", subscribedDesc: "Dziękujemy za subskrypcję. Będziesz otrzymywać aktualizacje o nowych zwierzętach, wydarzeniach i poradach.", stayUpdated: "Bądź na bieżąco", description: "Subskrybuj nasz newsletter, aby otrzymywać aktualizacje o nowych zwierzętach, wydarzeniach adopcyjnych i przydatnych poradach.", placeholder: "Wpisz swój e-mail", subscribe: "Subskrybuj", subscribing: "Subskrybuję...", privacy: "Szanujemy Twoją prywatność. Możesz zrezygnować w dowolnym momencie.", invalidEmail: "Nieprawidłowy e-mail", alreadySubscribed: "Już subskrybowany", alreadySubscribedDesc: "Ten e-mail jest już subskrybowany.", success: "Subskrybowano!", successDesc: "Zostałeś dodany do naszego newslettera.", failed: "Subskrypcja nie powiodła się", failedDesc: "Coś poszło nie tak. Spróbuj ponownie." },
  cta: { title: "Gotowy znaleźć nowego najlepszego przyjaciela?", description: "Tysiące zwierząt czeka na kochające domy. Rozpocznij swoją podróż adopcyjną już dziś.", browsePets: "Przeglądaj dostępne zwierzęta", learnAbout: "Dowiedz się o adopcji" },
  footer: { brandDesc: "Znajdujemy kochające domy dla zwierząt od 2020 roku. Każde zwierzę zasługuje na drugą szansę na szczęście.", quickLinks: "Szybkie linki", availablePets: "Dostępne zwierzęta", adoptionProcess: "Proces adopcji", successStories: "Historie sukcesu", volunteer: "Wolontariat", catBreeds: "Rasy kotów", dogBreeds: "Rasy psów", support: "Wsparcie", supportLink: "Wsparcie", donateLink: "Wspieraj", partnerWithUs: "Zostań partnerem", healthGuarantee: "Gwarancja zdrowia", deliveryOptions: "Opcje dostawy", emotionalSupport: "Wsparcie emocjonalne", privacyPolicy: "Polityka prywatności", termsConditions: "Regulamin", contactUs: "Skontaktuj się z nami", copyright: "© 2026 Pawsfam. Wszelkie prawa zastrzeżone. Stworzone z", forPets: "dla zwierząt na całym świecie." },
  common: { loading: "Ładowanie...", error: "Błąd", save: "Zapisz", cancel: "Anuluj", delete: "Usuń", edit: "Edytuj", back: "Wstecz", next: "Dalej", submit: "Wyślij", confirm: "Potwierdź", close: "Zamknij", search: "Szukaj", filter: "Filtruj", sortBy: "Sortuj po", noResults: "Brak wyników", viewDetails: "Zobacz szczegóły", learnMore: "Dowiedz się więcej" },
};

export default pl;
