const sv = {
  nav: { home: "Hem", adopt: "Adoptera", reviews: "Omdömen", foster: "Fosterhem", donate: "Donera", about: "Om oss", breeds: "Raser", catBreeds: "Kattraser", dogBreeds: "Hundraser", more: "Mer", deliveryOptions: "Leveransalternativ", healthGuarantee: "Hälsogaranti", emotionalSupport: "Emotionellt stöd", contact: "Kontakt", startAdopting: "Börja adoptera", admin: "Admin", orders: "Beställningar", signOut: "Logga ut", signIn: "Logga in", accountSettings: "Kontoinställningar", orderHistory: "Beställningshistorik", adminDashboard: "Admin-panel", currency: "Valuta", cart: "Varukorg", browsePets: "Bläddra djur", shoppingCart: "Varukorg", item: "artikel", items: "artiklar", yourCartEmpty: "Din varukorg är tom", deposit30: "30% handpenning", fullAdoption: "Fullständig adoption", moreItems: "+{{count}} fler artikel/artiklar", subtotal: "Delsumma", proceedToCheckout: "Gå till kassan" },
  hero: { badge: "Över 5 000 lyckade adoptioner", title1: "Hitta din", titleHighlight: "Perfekta", title2: "Kompanjon", description: "Varje djur förtjänar ett kärleksfullt hem. Bläddra bland hundratals älskvärda djur som väntar på sina familjer och gör skillnad idag.", browsePets: "Bläddra djur", learnMore: "Läs mer", petsAdopted: "Adopterade djur", verifiedShelters: "Verifierade shelter", support247: "Support", slideAlt: "Djurbildspel {{index}}", goToSlide: "Gå till bild {{index}}" },
  howItWorks: { label: "Enkel process", title: "Hur adoption fungerar", description: "Vi har gjort adoptionsprocessen enkel och stressfri. Så här kan du ta hem din nya bästa vän.", step1Title: "Bläddra djur", step1Desc: "Utforska vårt galleri av älskvärda djur som letar efter sina hem.", step2Title: "Ansök online", step2Desc: "Fyll i vår enkla adoptionsansökan med dina uppgifter.", step3Title: "Träffas", step3Desc: "Boka ett besök för att träffa din potentiella nya familjemedlem.", step4Title: "Välkommen hem", step4Desc: "Slutför adoptionen och ta hem din nya kompanjon!" },
  featured: { label: "Utvalda vänner", title: "Djur som väntar på dig", description: "Möt några av våra älskvärda djur som är redo att bli en del av din familj.", viewAllPets: "Visa alla djur", justAdded: "Nyligen tillagd", newArrivals: "Nykomlingar", newArrivalsDesc: "Kolla in de senaste djuren som letar efter sitt hem.", seeAllNewPets: "Visa alla nya djur", dogsLabel: "🐕 Hundar", dogsTitle: "Hundar tillgängliga för adoption", dogsDesc: "Hitta din perfekta hundkompanjon från vårt urval av älskvärda hundar.", viewAllDogs: "Visa alla hundar", catsLabel: "🐈 Katter", catsTitle: "Katter tillgängliga för adoption", catsDesc: "Upptäck söta och lekfulla katter som väntar på ett kärleksfullt hem.", viewAllCats: "Visa alla katter" },
  trust: { title: "Vi prioriterar etisk avel och djurvälfärd", description: "Vårt engagemang för excellens stöds av branschledande organisationer som sätter de högsta standarderna för djurvård och avelsmetoder.", cfaFull: "Cat Fanciers' Association", cfaDesc: "Världens största register för raskatter, som satt standarden för kattraser sedan 1906.", ticaFull: "Den Internationella Kattföreningen", ticaDesc: "Världens största genetiska register för ras- och huskatter, som främjar ansvarsfullt kattägande.", usdaFull: "USA:s jordbruksdepartement", usdaDesc: "Federal tillsynsmyndighet som säkerställer djurvälfärdsstandarder och hälsocertifieringar för djurtransport.", certifiedNote: "Alla våra uppfödare är certifierade och inspekteras regelbundet för att säkerställa de högsta vårdstandarderna." },
  journey: { label: "Din väg till sällskap", title: "Din adoptionsresa", description: "Vi har utformat en sömlös, omtänksam process för att säkerställa att du och din nya kompanjon passar perfekt ihop.", step1Title: "Upptäck och reservera", step1Desc: "Utforska våra omsorgsfullt uppfödda kattungar, var och en med en unik personlighet. Klicka på 'Reservera' när du hittar den perfekta matchningen.", step2Title: "Granskning och godkännande", step2Desc: "Efter reservation, fyll i ett kort livsstilsformulär. Våra specialister granskar det för bästa matchning.", step3Title: "Planera kattungens ankomst", step3Desc: "Vi koordinerar säker upphämtning eller leverans och ger förberedelsevägledning.", step4Title: "Veterinärgodkännande", step4Desc: "Varje kattunge måste vara minst 16 veckor gammal, korrekt vaccinerad, FIV/FELV-negativ, veterinärundersökt och ha giltigt hälsointyg.", step5Title: "Välkommen hem", step5Desc: "Ta emot din kattunge, medicinska journaler och fira detta speciella ögonblick med oss. Er resa tillsammans börjar!" },
  customerLove: { label: "Framgångshistorier", title: "Kundkärlek 💕", description: "Hör från familjer som hittat sina perfekta kompanjoner genom Pawsfam.", catParent: "Kattförälder", dogParent: "Hundförälder", seeAllReviews: "Se alla omdömen →" },
  newsletter: { subscribed: "Du är prenumerant!", subscribedDesc: "Tack för din prenumeration. Du kommer att få uppdateringar om nya djur, evenemang och adoptionstips.", stayUpdated: "Håll dig uppdaterad", description: "Prenumerera på vårt nyhetsbrev för uppdateringar om nya djur, adoptionsevenemang och nyttiga tips.", placeholder: "Ange din e-post", subscribe: "Prenumerera", subscribing: "Prenumererar...", privacy: "Vi respekterar din integritet. Avsluta när som helst.", invalidEmail: "Ogiltig e-post", alreadySubscribed: "Redan prenumerant", alreadySubscribedDesc: "Denna e-post prenumererar redan på vårt nyhetsbrev.", success: "Prenumererad!", successDesc: "Du har lagts till i vårt nyhetsbrev.", failed: "Prenumeration misslyckades", failedDesc: "Något gick fel. Försök igen." },
  cta: { title: "Redo att hitta din nya bästa vän?", description: "Tusentals djur väntar på kärleksfulla hem. Börja din adoptionsresa idag.", browsePets: "Bläddra bland tillgängliga djur", learnAbout: "Lär dig om adoption" },
  footer: { brandDesc: "Hittar kärleksfulla hem för djur sedan 2020. Varje djur förtjänar en andra chans till lycka.", quickLinks: "Snabblänkar", availablePets: "Tillgängliga djur", adoptionProcess: "Adoptionsprocess", successStories: "Framgångshistorier", volunteer: "Volontärarbete", catBreeds: "Kattraser", dogBreeds: "Hundraser", support: "Support", supportLink: "Support", donateLink: "Donera", partnerWithUs: "Bli partner", healthGuarantee: "Hälsogaranti", deliveryOptions: "Leveransalternativ", emotionalSupport: "Emotionellt stöd", privacyPolicy: "Integritetspolicy", termsConditions: "Villkor", contactUs: "Kontakta oss", copyright: "© 2026 Pawsfam. Alla rättigheter förbehållna. Gjord med", forPets: "för djur överallt." },
  common: { loading: "Laddar...", error: "Fel", save: "Spara", cancel: "Avbryt", delete: "Ta bort", edit: "Redigera", back: "Tillbaka", next: "Nästa", submit: "Skicka", confirm: "Bekräfta", close: "Stäng", search: "Sök", filter: "Filtrera", sortBy: "Sortera efter", noResults: "Inga resultat hittades", viewDetails: "Visa detaljer", learnMore: "Läs mer" },
};

export default sv;
