const tr = {
  nav: { home: "Ana Sayfa", adopt: "Sahiplen", reviews: "Yorumlar", foster: "Geçici Bakım", donate: "Bağış", about: "Hakkımızda", breeds: "Irklar", catBreeds: "Kedi Irkları", dogBreeds: "Köpek Irkları", more: "Daha Fazla", deliveryOptions: "Teslimat Seçenekleri", healthGuarantee: "Sağlık Garantisi", emotionalSupport: "Duygusal Destek", contact: "İletişim", startAdopting: "Sahiplenmeye Başla", admin: "Yönetici", orders: "Siparişler", signOut: "Çıkış", signIn: "Giriş", accountSettings: "Hesap Ayarları", orderHistory: "Sipariş Geçmişi", adminDashboard: "Yönetici Paneli", currency: "Para Birimi", cart: "Sepet", browsePets: "Hayvanları Gör", shoppingCart: "Alışveriş Sepeti", item: "ürün", items: "ürün", yourCartEmpty: "Sepetiniz boş", deposit30: "%30 Depozito", fullAdoption: "Tam Sahiplenme", moreItems: "+{{count}} ürün daha", subtotal: "Ara Toplam", proceedToCheckout: "Ödemeye Geç" },
  hero: { badge: "5.000'den fazla başarılı sahiplenme", title1: "Senin", titleHighlight: "Mükemmel", title2: "Arkadaşını Bul", description: "Her hayvan sevgi dolu bir yuvayı hak eder. Ailelerini bekleyen yüzlerce sevimli hayvanı keşfedin ve bugün fark yaratın.", browsePets: "Hayvanları Gör", learnMore: "Daha Fazla Bilgi", petsAdopted: "Sahiplenilen Hayvanlar", verifiedShelters: "Onaylı Barınaklar", support247: "Destek", slideAlt: "Hayvan slayt gösterisi {{index}}", goToSlide: "Slayt {{index}}'e git" },
  howItWorks: { label: "Basit Süreç", title: "Sahiplenme Nasıl Çalışır", description: "Sahiplenme sürecini basit ve stressiz hale getirdik. Yeni en iyi arkadaşınızı eve nasıl götüreceğiniz burada.", step1Title: "Hayvanları Gör", step1Desc: "Sonsuza kadar yuvalarını arayan sevimli hayvanlar galerimizi keşfedin.", step2Title: "Online Başvur", step2Desc: "Basit sahiplenme başvurumuzu bilgilerinizle doldurun.", step3Title: "Tanışma", step3Desc: "Potansiyel yeni aile üyenizle tanışmak için bir ziyaret planlayın.", step4Title: "Hoş Geldin Eve", step4Desc: "Sahiplenmeyi tamamlayın ve yeni arkadaşınızı eve götürün!" },
  featured: { label: "Öne Çıkan Dostlar", title: "Sizi Bekleyen Hayvanlar", description: "Ailenizin bir parçası olmaya hazır sevimli hayvanlarımızla tanışın.", viewAllPets: "Tüm Hayvanları Gör", justAdded: "Yeni Eklendi", newArrivals: "Yeni Gelenler", newArrivalsDesc: "Sonsuza kadar yuvalarını arayan en yeni hayvanları keşfedin.", seeAllNewPets: "Tüm Yeni Hayvanları Gör", dogsLabel: "🐕 Köpekler", dogsTitle: "Sahiplenmeye Hazır Köpekler", dogsDesc: "Sevimli köpekler arasından mükemmel köpek arkadaşınızı bulun.", viewAllDogs: "Tüm Köpekleri Gör", catsLabel: "🐈 Kediler", catsTitle: "Sahiplenmeye Hazır Kediler", catsDesc: "Sevgi dolu bir yuva bekleyen tatlı ve oyuncu kedileri keşfedin.", viewAllCats: "Tüm Kedileri Gör" },
  trust: { title: "Etik Yetiştirme ve Hayvan Refahını Ön Planda Tutuyoruz", description: "Mükemmelliğe olan bağlılığımız, hayvan bakımı ve yetiştirme uygulamalarında en yüksek standartları belirleyen sektör lideri kuruluşlar tarafından desteklenmektedir.", cfaFull: "Kedi Severler Derneği", cfaDesc: "1906'dan beri kedi ırkları standardını belirleyen dünyanın en büyük soy kedi kayıt kuruluşu.", ticaFull: "Uluslararası Kedi Derneği", ticaDesc: "Sorumlu kedi sahipliğini teşvik eden dünyanın en büyük soy ve ev kedisi genetik kayıt kuruluşu.", usdaFull: "ABD Tarım Bakanlığı", usdaDesc: "Hayvan taşımacılığı için hayvan refahı standartlarını ve sağlık sertifikalarını sağlayan federal düzenleyici kuruluş.", certifiedNote: "Tüm yetiştiricilerimiz sertifikalıdır ve en yüksek bakım standartlarını sağlamak için düzenli olarak denetlenir." },
  journey: { label: "Arkadaşlığa Giden Yolunuz", title: "Sahiplenme Yolculuğunuz", description: "Siz ve yeni arkadaşınızın mükemmel uyum sağlaması için sorunsuz, özenli bir süreç tasarladık.", step1Title: "Keşfet ve Rezerve Et", step1Desc: "Her biri benzersiz bir kişiliğe sahip özenle yetiştirilmiş yavru kedilerimizi keşfedin. Mükemmel eşleşmeyi bulduğunuzda 'Rezerve Et'e tıklayın.", step2Title: "İnceleme ve Onay", step2Desc: "Rezervasyondan sonra kısa bir yaşam tarzı anketi doldurun. Uzmanlarımız en iyi eşleşme için inceler.", step3Title: "Yavru Kedinin Gelişini Planlayın", step3Desc: "Güvenli teslim alma veya teslimat koordine ederiz ve yeni aile üyeniz için hazırlık rehberliği sağlarız.", step4Title: "Veteriner Onayı", step4Desc: "Her yavru kedi en az 16 haftalık olmalı, düzgün aşılanmış, FIV/FELV negatif, veteriner kontrolünden geçmiş ve geçerli sağlık sertifikasına sahip olmalıdır.", step5Title: "Hoş Geldin Eve", step5Desc: "Yavru kedinizi, tıbbi kayıtları alın ve bu özel anı bizimle kutlayın. Birlikte yolculuğunuz başlıyor!" },
  customerLove: { label: "Başarı Hikayeleri", title: "Müşteri Sevgisi 💕", description: "Pawsfam aracılığıyla mükemmel arkadaşlarını bulan ailelerin hikayelerini dinleyin.", catParent: "Kedi Ebeveyni", dogParent: "Köpek Ebeveyni", seeAllReviews: "Tüm Yorumları Gör →" },
  newsletter: { subscribed: "Abone Oldunuz!", subscribedDesc: "Abone olduğunuz için teşekkürler. Yeni hayvanlar, etkinlikler ve sahiplenme ipuçları hakkında güncellemeler alacaksınız.", stayUpdated: "Güncel Kalın", description: "Yeni hayvanlar, sahiplenme etkinlikleri ve hayvan sahipleri için faydalı ipuçları hakkında güncellemeler almak için bültenimize abone olun.", placeholder: "E-postanızı girin", subscribe: "Abone Ol", subscribing: "Abone olunuyor...", privacy: "Gizliliğinize saygı duyuyoruz. İstediğiniz zaman aboneliği iptal edebilirsiniz.", invalidEmail: "Geçersiz e-posta", alreadySubscribed: "Zaten abone", alreadySubscribedDesc: "Bu e-posta zaten bültenimize abone.", success: "Abone olundu!", successDesc: "Bültenimize eklendiniz.", failed: "Abonelik başarısız", failedDesc: "Bir şeyler yanlış gitti. Lütfen tekrar deneyin." },
  cta: { title: "Yeni En İyi Arkadaşınızı Bulmaya Hazır Mısınız?", description: "Binlerce hayvan sevgi dolu yuvalar bekliyor. Sahiplenme yolculuğunuza bugün başlayın.", browsePets: "Mevcut Hayvanları Gör", learnAbout: "Sahiplenme Hakkında Bilgi" },
  footer: { brandDesc: "2020'den beri hayvanlara sevgi dolu yuvalar buluyoruz. Her hayvan ikinci bir mutluluk şansını hak eder.", quickLinks: "Hızlı Bağlantılar", availablePets: "Mevcut Hayvanlar", adoptionProcess: "Sahiplenme Süreci", successStories: "Başarı Hikayeleri", volunteer: "Gönüllülük", catBreeds: "Kedi Irkları", dogBreeds: "Köpek Irkları", support: "Destek", supportLink: "Destek", donateLink: "Bağış", partnerWithUs: "Bizimle Ortak Olun", healthGuarantee: "Sağlık Garantisi", deliveryOptions: "Teslimat Seçenekleri", emotionalSupport: "Duygusal Destek", privacyPolicy: "Gizlilik Politikası", termsConditions: "Şartlar ve Koşullar", contactUs: "Bize Ulaşın", copyright: "© 2026 Pawsfam. Tüm hakları saklıdır.", forPets: "Her yerdeki hayvanlar için yapıldı." },
  common: { loading: "Yükleniyor...", error: "Hata", save: "Kaydet", cancel: "İptal", delete: "Sil", edit: "Düzenle", back: "Geri", next: "İleri", submit: "Gönder", confirm: "Onayla", close: "Kapat", search: "Ara", filter: "Filtrele", sortBy: "Sırala", noResults: "Sonuç bulunamadı", viewDetails: "Detayları Gör", learnMore: "Daha Fazla Bilgi" },
};

export default tr;
