const zh = {
  nav: { home: "首页", adopt: "领养", reviews: "评价", foster: "寄养", donate: "捐赠", about: "关于我们", breeds: "品种", catBreeds: "猫品种", dogBreeds: "犬品种", more: "更多", deliveryOptions: "配送选项", healthGuarantee: "健康保证", emotionalSupport: "情感支持", contact: "联系我们", startAdopting: "开始领养", admin: "管理", orders: "订单", signOut: "退出", signIn: "登录", accountSettings: "账户设置", orderHistory: "订单历史", adminDashboard: "管理面板", currency: "货币", cart: "购物车", browsePets: "浏览宠物", shoppingCart: "购物车", item: "件", items: "件", yourCartEmpty: "您的购物车为空", deposit30: "30%定金", fullAdoption: "全额领养", moreItems: "+{{count}}件更多", subtotal: "小计", proceedToCheckout: "去结算" },
  hero: { badge: "超过5,000次成功领养", title1: "找到你的", titleHighlight: "完美", title2: "伴侣", description: "每只宠物都值得一个温暖的家。浏览数百只等待家庭的可爱宠物，今天就做出改变。", browsePets: "浏览宠物", learnMore: "了解更多", petsAdopted: "已领养宠物", verifiedShelters: "认证收容所", support247: "客服支持", slideAlt: "宠物幻灯片 {{index}}", goToSlide: "转到幻灯片 {{index}}" },
  howItWorks: { label: "简单流程", title: "领养如何运作", description: "我们让领养过程变得简单轻松。以下是如何将您的新好朋友带回家。", step1Title: "浏览宠物", step1Desc: "探索我们的可爱宠物画廊，寻找它们永远的家。", step2Title: "在线申请", step2Desc: "填写我们简单的领养申请表。", step3Title: "见面", step3Desc: "安排参观，认识您潜在的新家庭成员。", step4Title: "欢迎回家", step4Desc: "完成领养，将您的新伙伴带回家！" },
  featured: { label: "推荐朋友", title: "等待您的宠物", description: "认识一些准备成为您家庭一员的可爱宠物。", viewAllPets: "查看所有宠物", justAdded: "新添加", newArrivals: "新到宠物", newArrivalsDesc: "查看最新寻找家的宠物。", seeAllNewPets: "查看所有新宠物", dogsLabel: "🐕 狗", dogsTitle: "可领养的狗", dogsDesc: "从我们可爱的狗选集中找到您完美的犬类伙伴。", viewAllDogs: "查看所有狗", catsLabel: "🐈 猫", catsTitle: "可领养的猫", catsDesc: "发现等待温暖家庭的甜美活泼的猫。", viewAllCats: "查看所有猫" },
  trust: { title: "我们优先考虑道德繁殖和动物福利", description: "我们对卓越的承诺得到了行业领先组织的支持，这些组织为动物护理和繁殖实践制定了最高标准。", cfaFull: "猫爱好者协会", cfaDesc: "世界上最大的纯种猫注册机构，自1906年以来为猫品种制定标准。", ticaFull: "国际猫协会", ticaDesc: "世界上最大的纯种猫和家猫基因注册机构，推动负责任的猫饲养。", usdaFull: "美国农业部", usdaDesc: "确保动物福利标准和宠物运输健康认证的联邦监管机构。", certifiedNote: "我们所有的繁殖者都经过认证并定期检查，以确保最高的护理标准。" },
  journey: { label: "您的陪伴之路", title: "您的领养之旅", description: "我们设计了一个无缝、贴心的流程，确保您和新伙伴完美匹配。", step1Title: "发现和预订", step1Desc: "探索我们精心培育的小猫，每只都有独特的性格。找到完美匹配后点击'预订'。", step2Title: "审核与批准", step2Desc: "预订后，完成简短的生活方式问卷。我们的专家会审核以确保最佳匹配。", step3Title: "计划小猫到达", step3Desc: "我们协调安全的接送或递送，并提供新家庭成员的准备指导。", step4Title: "兽医检查", step4Desc: "每只小猫必须至少16周大，正确接种疫苗，FIV/FELV阴性，经兽医检查并持有有效健康证明。", step5Title: "欢迎回家", step5Desc: "接收您的小猫、医疗记录，与我们一起庆祝这个特别时刻。你们的旅程开始了！" },
  customerLove: { label: "成功故事", title: "客户的爱 💕", description: "听听通过Pawsfam找到完美伴侣的家庭故事。", catParent: "猫主人", dogParent: "狗主人", seeAllReviews: "查看所有评价 →" },
  newsletter: { subscribed: "您已订阅！", subscribedDesc: "感谢您的订阅。您将收到关于新宠物、活动和领养建议的更新。", stayUpdated: "保持更新", description: "订阅我们的通讯以获取新宠物、领养活动和宠物主人有用提示的更新。", placeholder: "输入您的邮箱", subscribe: "订阅", subscribing: "订阅中...", privacy: "我们尊重您的隐私。随时可以取消订阅。", invalidEmail: "无效邮箱", alreadySubscribed: "已订阅", alreadySubscribedDesc: "此邮箱已订阅我们的通讯。", success: "已订阅！", successDesc: "您已添加到我们的通讯。", failed: "订阅失败", failedDesc: "出了些问题。请重试。" },
  cta: { title: "准备好找到你的新好朋友了吗？", description: "数千只宠物正等待温暖的家。今天就开始你的领养之旅。", browsePets: "浏览可领养宠物", learnAbout: "了解领养" },
  footer: { brandDesc: "自2020年以来为宠物寻找温暖的家。每只宠物都值得第二次幸福的机会。", quickLinks: "快速链接", availablePets: "可领养宠物", adoptionProcess: "领养流程", successStories: "成功故事", volunteer: "志愿者", catBreeds: "猫品种", dogBreeds: "犬品种", support: "支持", supportLink: "支持", donateLink: "捐赠", partnerWithUs: "与我们合作", healthGuarantee: "健康保证", deliveryOptions: "配送选项", emotionalSupport: "情感支持", privacyPolicy: "隐私政策", termsConditions: "条款与条件", contactUs: "联系我们", copyright: "© 2026 Pawsfam。保留所有权利。用", forPets: "为各地的宠物而制作。" },
  common: { loading: "加载中...", error: "错误", save: "保存", cancel: "取消", delete: "删除", edit: "编辑", back: "返回", next: "下一步", submit: "提交", confirm: "确认", close: "关闭", search: "搜索", filter: "筛选", sortBy: "排序", noResults: "未找到结果", viewDetails: "查看详情", learnMore: "了解更多" },
};

export default zh;
